microsoft/beachball

- packages/beachball/src/ChangeInfo.ts
- packages/beachball/src/bump.ts
- packages/beachball/src/changefile.ts
- packages/beachball/src/changelog.ts
- packages/beachball/src/monorepo.ts
- packages/beachball/src/publish.ts
Partial fix for #21.  I only expose the prerelease type if a package is already using a prerelease version number. -- which avoids adding the additional question and format change of storing the prerelease name.
I also added the ability for packages to disable changetypes on a per package basis.  -- I'm open to where to store that setting.  Currently its as a prop in package.json.
> Add prerelease option

- packages/beachball/src/changefile.ts
- packages/beachball/src/getChangedPackages.ts
- packages/website/content/docs/overview/configuration.md
- packages/website/content/docs/table-of-contents.json
- Adds a new option that packages can specify in their package.json to have beachball ignore that package.  This package would be ignored the same as if the package was marked as private.
- Fixes #1  by bolding the changetype in the choices menu.
- Fixes #28 by adding some documentation.
> Allow packages to opt out of publishing

- README.md
- change/beachball-2019-08-21-16-55-19-dontPublishPrivate.json
- packages/beachball/src/bump.ts
- packages/beachball/src/changefile.ts
- packages/beachball/src/monorepo.ts
Right now we assume that all valid packages mentioned in change files should be published to, but some of the packages - though valid - are private and should not be valid. This check filters our operational package information to only public ones.
> Don't publish private packages

- change/beachball-2019-09-03-12-47-10-uncommitted.json
- packages/beachball/src/cli.ts
- packages/beachball/src/getChangedPackages.ts
- packages/beachball/src/git.ts
#107 brought to the attention that during publish build jobs, uncommitted files can be generated. This should in no way affect `beachball check` or `beachball publish`. This change brings two features:
1. allows untracked files to be present - would not count towards change checks or publish. CAVEAT: those changes are published to npm registry as well, but will be lost from origin git repo after publish unless explicitly pushed by another process
2. allows staged files to be counted towards change file prompts - this can allow someone to work on the change file before the commit of the feature
> Allow uncommitted changes as well as allowing staged changes

- change/beachball-2019-10-04-08-03-36-private.json
- packages/beachball/src/PackageInfo.ts
- packages/beachball/src/bump.ts
- packages/beachball/src/changefile.ts
- packages/beachball/src/fixtures/package.ts
- packages/beachball/src/monorepo.ts
- packages/beachball/src/publish.ts
Through some manual testing, private package publishes causes the publish to try to delete the change files for those private packages still. We should skip those actions as well as tagging.
> Ignore private package publishing

- change/beachball-2019-11-04-15-51-13-delete.json
- packages/beachball/src/CliOptions.ts
- packages/beachball/src/bump.ts
- packages/beachball/src/changefile.ts
- packages/beachball/src/cli.ts
- packages/beachball/src/publish.ts
Currently, if a package only has "none" type change files, the publish process does not even run the bump. This change allows the publish step to run and will delete the none change files.
> deletes none type change files

- change/beachball-2020-01-16-11-55-27-propagate.json
- packages/beachball/src/__e2e__/bump.test.ts
- packages/beachball/src/__tests__/bump/updateRelatedChangeType.test.ts
- packages/beachball/src/bump/updateRelatedChangeType.ts
I've also added an example of this in an unit test. The example is drawn / inspired by UI Fabric's orgnaization.
> Propagate dependent package change type

- .vscode/launch.json
- change/beachball-2020-03-03-14-54-02-scoped-check.json
- packages/beachball/src/__e2e__/monorepo/getScopedPackages.test.ts
- packages/beachball/src/__e2e__/validation.test.ts
- packages/beachball/src/changefile/getChangedPackages.ts
- packages/beachball/src/changefile/promptForChange.ts
- packages/beachball/src/fixtures/exec.ts
- packages/beachball/src/fixtures/monorepo.ts
- packages/beachball/src/fixtures/repository.ts
- packages/beachball/src/fixtures/tmpdir.ts
- packages/beachball/src/monorepo/getPackageInfos.ts
- packages/beachball/src/monorepo/getScopedPackages.ts
- packages/beachball/src/options/getCliOptions.ts
- packages/beachball/src/options/getDefaultOptions.ts
- packages/beachball/src/types/BeachballOptions.ts
- packages/beachball/src/validation/isChangeFileNeeded.ts
- packages/beachball/src/validation/validate.ts
In this change, we added a param called "scope". For now, it applies to change and check so that those commands can make checks / change files only for scoped packages.
For example: 
```
beachball change --scope packages/grouped/*
```
> This adds a --scope for check and change that can be applied to repos that manages several groups of packages

- change/beachball-2020-03-05-08-56-01-star.json
- packages/beachball/src/__tests__/bump/bumpMinSemverRange.test.ts
- packages/beachball/src/bump/bumpMinSemverRange.ts
This PR will allow star ranges to be preserved when bumping logic happens.
> Hey now you're an all star

- change/beachball-2020-03-06-15-22-54-xgao-publish-fix.json
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/publish/publishToRegistry.ts
- packages/beachball/src/publish/validatePackageVersions.ts
To fix :
https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=56802&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=0db80ebc-3da9-5105-8df1-43c3063dee76&l=153
`modifiedPackages` can included the out-of-scoped package bc we still update `dependencies` for scoped out package
> Scoped publish: make sure to skip validation/publish for out-of-scope package

- .vscode/launch.json
- change/beachball-2020-03-20-13-12-52-xgao-fix-disallow-type-groups.json
- packages/beachball/src/__tests__/bump/updateRelatedChangeType.test.ts
- packages/beachball/src/__tests__/changefile/getPackageChangeTypes.test.ts
- packages/beachball/src/bump/updateRelatedChangeType.ts
- packages/beachball/src/changefile/promptForChange.ts
- packages/beachball/src/monorepo/getPackageGroups.ts
- packages/beachball/src/types/PackageInfo.ts
- packages/beachball/src/validation/isValidGroupOptions.ts
Currently when prompting change type for change files, we only filter using `disallowedChangeTypes` defined at top level. Instead we should be looking at the `disallowedChangeTypes` defined in version groups as well.
> Fix promptChangeFiles to honor disallowedChangeTypes defined in version groups

- change/beachball-2020-03-20-16-02-29-xgao-version-group-fix.json
- packages/beachball/src/__tests__/bump/updateRelatedChangeType.test.ts
- packages/beachball/src/bump/updateRelatedChangeType.ts
- packages/beachball/src/changefile/getPackageChangeTypes.ts
- packages/beachball/src/changefile/promptForChange.ts
when a package inside a group is bumped with `none` change type, it's always bumped as `patch` due to we use `patch` as default in `updateRelatedChangeType`
also fixed default `dependentChangeType` value in change file. if change is `none`, do not set `dependentChangeType` to `patch`
> Fix version group bumping with none change type

- .vscode/settings.json
- change/beachball-2020-03-21-04-55-51-infer-commit.json
- packages/beachball/src/__e2e__/bump.test.ts
- packages/beachball/src/__e2e__/changelog.test.ts
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/__e2e__/publishGit.test.ts
- packages/beachball/src/__e2e__/publishRegistry.test.ts
- packages/beachball/src/changefile/getChangedPackages.ts
- packages/beachball/src/changefile/getPackageChangeTypes.ts
- packages/beachball/src/changefile/promptForChange.ts
- packages/beachball/src/changefile/readChangeFiles.ts
- packages/beachball/src/changefile/writeChangeFiles.ts
- packages/beachball/src/fixtures/exec.ts
- packages/beachball/src/fixtures/repository.ts
- packages/beachball/src/fixtures/tmpdir.ts
- packages/beachball/src/git/index.ts
- packages/beachball/src/types/ChangeInfo.ts
Currently beachball records the most recent commit hash when a change file is created, but that causes problems in some cases, such as if you rebase after creating the change file. It also makes it harder to link a change file to a particular GitHub PR since the referenced commit may not exist in history if the repo squashes PRs.
This PR removes the commit hash from the change files, and instead infers it while generating the changelog, based on the actual commit hash that introduced the change file.
Also add a call to `tmp.setGracefulCleanup()` to ensure test repos are actually cleaned up.
> Infer commit hash from change file introduction commit

- change/beachball-2020-03-23-13-52-29-xgao-changelog-1.json
- packages/beachball/src/options/getOptions.ts
- packages/beachball/src/types/BeachballOptions.ts
We will later add options such as:
`enablePRLink` to enable adding PR link for each change (#274)
`groups` to enable generating aggregated change log for multiple packages (#277)
Note: parsing logic is already done in `getRootOptions`
> ChangeLog: add empty options interface

- change/beachball-2020-03-24-16-57-33-xgao-changelog-group.json
- packages/beachball/src/__e2e__/changelog.test.ts
- packages/beachball/src/__tests__/changelog/mergeChangelogs.test.ts
- packages/beachball/src/__tests__/monorepo/utils.test.ts
- packages/beachball/src/bump/performBump.ts
- packages/beachball/src/changelog/getPackageChangelogs.ts
- packages/beachball/src/changelog/mergeChangelogs.ts
- packages/beachball/src/changelog/renderChangelog.ts
- packages/beachball/src/changelog/renderPackageChangelog.ts
- packages/beachball/src/changelog/writeChangelog.ts
- packages/beachball/src/monorepo/getPackageGroups.ts
- packages/beachball/src/monorepo/getScopedPackages.ts
- packages/beachball/src/monorepo/utils.ts
- packages/beachball/src/types/BeachballOptions.ts
- packages/beachball/src/types/ChangeLog.ts
- packages/beachball/src/validation/isValidChangelogOptions.ts
- packages/beachball/src/validation/validate.ts
Address issue #277
Say we have:
```
\pacakges
--\foo
----\foo-change-file.json
\pacakges
--\bar
----\bar-change-file.json
```
in `foo-change-file.json`:
```
{
"type": "patch",
"comment": "make a change in foo",
"packageName": "foo",
"email": "xgao@microsoft.com",
"dependentChangeType": "patch",
"date": "2020-03-24T18:40:15.042Z"
}
```
in `bar-change-file.json`: 
```
{
"type": "patch",
"comment": "make a change in bar",
"packageName": "bar",
"email": "xgao@microsoft.com",
"dependentChangeType": "patch",
"date": "2020-03-24T18:40:15.042Z"
}
```
if we define to create grouped change file with new changelog beachball option:
```
"beachball": {
"changelog": {
"groups": [
{
"masterPackageName": "foo",
"changelogPath": "packages",
"include": [
"packages/foo",
"packages/bar",
]
}
]
},
``` …
> ChangeLog: support grouped change log generation

- change/beachball-2020-03-27-09-52-31-xgao-fix-test.json
- packages/beachball/src/changefile/readChangeFiles.ts
Change log entires ordering change because change files are read in nondeterministic order.
test failure: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=61612&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997
> fix unstable tests by having change files read in deterministic order

- change/beachball-2020-03-26-17-18-49-manual-recovery.json
- packages/beachball/src/packageManager/npm.ts
- packages/beachball/src/publish/displayManualRecovery.ts
- packages/beachball/src/publish/publishToRegistry.ts
If publishing failed partway through but some packages succeeded, the manual recovery message should list the packages that succeeded (with a warning that they might be broken). Fixes #291.
When spawning publish process, increase `maxBuffer` to `1024 * 1024` so that packages with lots of files don't cause the process to be killed. (This is the default in newer Node versions, but version 10 still has a default of only 200k.) Fixes #293.
> Improve manual recovery message if some packages succeeded; allow longer output

- README.md
- change/beachball-2020-03-24-17-36-31-readme.json
- packages/beachball/README.md
Copy the readme from the root to the beachball package so it gets published with the npm package.
This might be a good example of a place where pre-release scripts would be useful, so we can have only one copy of this file checked in. :)
> Add a readme back to the beachball package

- change/beachball-2020-03-30-12-36-52-retries.json
- packages/beachball/package.json
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/__e2e__/publishGit.test.ts
- packages/beachball/src/__e2e__/publishRegistry.test.ts
- packages/beachball/src/options/getDefaultOptions.ts
- packages/beachball/src/packageManager/packagePublish.ts
- packages/beachball/src/publish/publishToRegistry.ts
- packages/beachball/src/types/BeachballOptions.ts
This fixes #290 - sometimes publishes fail due to network conditions. This retry will add resiliency to the publish process.
> Adds an option to allow package publishes to be retried

- change/beachball-2020-03-30-13-44-57-xgao-custom-change-type-prompt.json
- packages/beachball/src/changefile/promptForChange.ts
- packages/beachball/src/types/BeachballOptions.ts
- packages/beachball/src/types/ChangeFilePrompt.ts
Enable customizing the prompt with the following:
1. description for each change type 
2. add change area prompt
For instance:
Beachball options:
```
changeFilePrompt: {
changePrompt: prompt => {
const { changeType } = prompt;
changeType.choices &&
changeType.choices.forEach(choice => {
if (choice.value === 'patch') {
choice.title = ' [1mPatch[22m      - Changes that bumps packge with patch version.';
} else if (choice.value === 'minor') {
choice.title = ' [1mMinor[22m      - Changes that bumps packge with minor version.';
}
});
const changeAreaPrompt = {
type: 'select',
name: 'area',
message: 'Change area',
choices: [
{ value: 'fix', title: 'Bug fix' },
{ value: 'perf', title: 'Performance' },
{ value: 'doc', title: 'Documentation' },
],
};
return [prompt.changeType, …
```
> Change file prompt: support customizing prompt questions

- README.md
- change/beachball-2020-03-30-14-47-30-sync.json
- packages/beachball/README.md
- packages/beachball/src/cli.ts
- packages/beachball/src/commands/sync.ts
- packages/beachball/src/help.ts
- packages/beachball/src/publish/displayManualRecovery.ts
Fixes a long standing feature request: #29 
In the event of a partial publish failure, it is tedious to have to find out which package versions to sync. This automates the procedure. This script does NOT unpublish old partially published versions, however.
> adding a sync command to help recover

- change/beachball-2020-04-01-20-18-37-e2e-cleanup.json
- packages/beachball/src/__e2e__/bump.test.ts
- packages/beachball/src/__e2e__/changelog.test.ts
- packages/beachball/src/__e2e__/monorepo/getScopedPackages.test.ts
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/__e2e__/publishGit.test.ts
- packages/beachball/src/__e2e__/publishRegistry.test.ts
- packages/beachball/src/__e2e__/validation.test.ts
- packages/beachball/src/fixtures/exec.ts
- packages/beachball/src/fixtures/monorepo.ts
- packages/beachball/src/fixtures/repository.ts
- packages/beachball/src/fixtures/tmpdir.ts
For some reason `tmp` isn't cleaning up its files when run within jest, even with the (needlessly obscure) cleanup options enabled. So all the e2e tests should do manual cleanup instead.
Easiest way to do this is add a cleanup method on RepositoryFactory which deletes all repos created by that factory, and call it in each test (usually in afterAll).
> e2e tests should clean up properly

- .vscode/launch.json
- change/beachball-2020-03-27-18-25-51-changelog-render.json
- packages/beachball/package.json
- packages/beachball/src/__e2e__/__snapshots__/changelog.test.ts.snap
- packages/beachball/src/__e2e__/bump.test.ts
- packages/beachball/src/__e2e__/changelog.test.ts
- packages/beachball/src/__tests__/changelog/__snapshots__/renderChangelog.test.ts.snap
- packages/beachball/src/__tests__/changelog/__snapshots__/renderPackageChangelog.test.ts.snap
- packages/beachball/src/__tests__/changelog/mergeChangelogs.test.ts
- packages/beachball/src/__tests__/changelog/renderChangelog.test.ts
- packages/beachball/src/__tests__/changelog/renderPackageChangelog.test.ts
- packages/beachball/src/bump/performBump.ts
- packages/beachball/src/changefile/getPackageChangeTypes.ts
- packages/beachball/src/changelog/getPackageChangelogs.ts
- packages/beachball/src/changelog/mergeChangelogs.ts
- packages/beachball/src/changelog/renderChangelog.ts
- packages/beachball/src/changelog/renderJsonChangelog.ts
- packages/beachball/src/changelog/renderPackageChangelog.ts
- packages/beachball/src/changelog/writeChangelog.ts
- packages/beachball/src/cli.ts
- packages/beachball/src/commands/bump.ts
- packages/beachball/src/commands/publish.ts
- packages/beachball/src/publish/bumpAndPush.ts
- packages/beachball/src/publish/publishToRegistry.ts
- packages/beachball/src/types/BeachballOptions.ts
- packages/beachball/src/types/ChangeLog.ts
- packages/beachball/src/types/ChangelogOptions.ts
- packages/beachball/src/validation/isValidChangelogOptions.ts
- yarn.lock
Add fine-grained custom render functions for the changelog markdown. This way if someone wants to just modify one little part, they don't have to re-create the entire rendering logic. 
Variant of @xugao's PR #289.
Example:
```js
module.exports = {
// ...
changelogOptions: {
customRenderers: {
renderHeader: (renderInfo) => {
return [
`## ${renderInfo.newPackageVersion.version}`, 
renderInfo.newPackageVersion.date.toUTCString(),
`[Compare changes](${/*get compare link*/})`
].join('\n');
},
renderEntry: (entry, renderInfo) =>
`- ${entry.comment} (${entry.author}, PR #${/*get PR number*/})`
}
}
};
```
Also add the git tag to CHANGELOG.json, which was part of Xu's change.
> Add custom render functions for changelog parts

- change/beachball-2020-04-02-18-05-18-export-types.json
- packages/beachball/package.json
- packages/beachball/src/index.ts
Export types which might be used in a config file or custom renderers from a new file `src/index.ts`.
> Export public-facing types from root

- change/beachball-2020-04-08-16-33-06-fix-infer-commit.json
- packages/beachball/src/changefile/readChangeFiles.ts
The git log command to get the hash was running on the `change` folder, not the changefile itself.
> Fix a bug with inferring the commit hash

- change/beachball-2020-04-13-15-18-11-scale.json
- packages/beachball/src/git/index.ts
- packages/beachball/src/monorepo/getPackageInfos.ts
We are hitting scale issues if the total # of files goes above a threshold - SIGTERM is applied to a ls-tree
> Scale - use the ls-files command to search a pattern in git rather than filter with node

- change/beachball-2020-04-15-14-48-23-hooks.json
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/publish/publishToRegistry.ts
- packages/beachball/src/types/BeachballOptions.ts
In this PR, we add the ability to have hooks specifically from beachball.config.js.
1. These hooks are repo wide right now
2. There is only one prepublish hook right now
3. The hook is expected to be side effects heavy, being passed in a bumpInfo
4. if bumpInfo is modified, the bumpInfo is used during npm publish only
5. git push happens against original gather bump info process without prepublish
> Hooks: adding support for prepublish steps

- change/beachball-2020-04-17-14-27-42-xgao-reduce-log.json
- packages/beachball/src/packageManager/packagePublish.ts
Along the lines of fixing #293 and increasing max buffer size
> reduce npm publish log by set loglevel to warn

- change/beachball-2020-04-17-10-47-58-xgao-sort-publish.json
- packages/beachball/package.json
- packages/beachball/src/__tests__/publish/toposortPackages.test.ts
- packages/beachball/src/publish/publishToRegistry.ts
- packages/beachball/src/publish/toposortPackages.ts
- yarn.lock
Fixes #322
if dependent publishes first and dependencies failed to publish, we ended up publishing packages which are not installable for users.
Do a topological sort on the packages before publishing them to guarantee dependencies are published before dependent.
> Publish packages in the right order based on dependency graph

- change/beachball-2020-04-17-16-33-59-pre-publish.json
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/fixtures/monorepo.ts
- packages/beachball/src/publish/publishToRegistry.ts
- packages/beachball/src/types/BeachballOptions.ts
The first iteration on the prepublish hook allowed for modifying bumpInfo.  This happened during publish before packages were bumped.  While it allowed for modifying versions the implementation comes with some issues:
- it only worked for certain fields like version, changes to other information wouldn't be reflected in the files
- it happens before the last batch of changes are committed to the package.json files, this means that modification in bumpInfo, were they to be respected, might conflict
- it leaks too much in the way of internal implementation details
- it doesn't address the desire to make modifications to package.json that only apply to published files
Eventually the old prepublish hook could reappear as a prebump hook with a more deterministic API such as one that has a …
> Change prepublish hook to be file based and happen per-package

- change/beachball-2020-04-20-01-01-13-reli-fix-multiple-package-publishing.json
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/__e2e__/publishRegistry.test.ts
- packages/beachball/src/publish/publishToRegistry.ts
Fixes #327 .
The current `return` when after package is successfully published will stop Beachball to publish other packages if multiple packages needs to publish to the registry. This change fixes this regression introduced by #299 .
> Fix multi-package publishing regression (#327).

- change/beachball-2020-04-30-12-25-25-check-changetype.json
- packages/beachball/src/changefile/readChangeFiles.ts
- packages/beachball/src/validation/validate.ts
`beachball check` needs to validate all change files that have been created inside the repo. Change can occur where someone manually made a typo in the change type.
> Check changetype beyond the command line

- change/beachball-2020-06-03-09-54-09-publish-error-log.json
- packages/beachball/src/__e2e__/publishRegistry.test.ts
- packages/beachball/src/publish/publishToRegistry.ts
If a publish attempt fails, log errors for every attempt, not just the last one.
> publish: log errors for each retry attempt

- change/beachball-2020-06-23-03-29-15-package-git-tags.json
- packages/beachball/src/__e2e__/packageManager.test.ts
- packages/beachball/src/__tests__/publish/tagPackages.test.ts
- packages/beachball/src/fixtures/package.ts
- packages/beachball/src/publish/bumpAndPush.ts
- packages/beachball/src/publish/tagPackages.ts
- packages/beachball/src/types/BeachballOptions.ts
This builds upon #346 and exposes gitTags as an option in package.json. This is useful for monorepos which only want one package to show up in their release view.
This is populated according to the existing rules of `getPackageOptions`, meaning the option we will see precedence of:
1. Cli options
2. Local package
3. Root package
4. Default options (tag)
> Allow Individual Packages to Opt Out of Git Tags

- change/beachball-2020-08-03-21-50-54-arabisho-adding-since-flag-for-change-file-deltas.json
- packages/beachball/src/__e2e__/bump.test.ts
- packages/beachball/src/changefile/readChangeFiles.ts
- packages/beachball/src/git/index.ts
- packages/beachball/src/help.ts
- packages/beachball/src/options/getCliOptions.ts
- packages/beachball/src/types/BeachballOptions.ts
This PR includes implementation of the `--since` flag that allows users to specify a range of change files used by the `bump` and `publish` commands. The value passed to the `--since` flag can be any git ref, i.e. commit SHA, branch name or tag. 
**Behaviour of `bump --since <ref>`:** with `bump --since C1` executed for the repo containing `C1 <- C2 <- C3` commits, `bump` is going to pick-up change files introduced in commits C2 and C3. Once versions are bumped, corresponding change files will be deleted.
**Behaviour of `publish --since <ref>`:** similar to `bump --since <ref`, with the difference that publish is going to upload affected packages to an npm registry.
The flag does not affect the behaviour of `check`, `change` or `sync` commands. This PR implements part of a
solution for …
> --since flag implementation for bump and publish commands

- change/beachball-2020-08-05-21-57-19-arabisho-adding-keep-change-files-flag.json
- packages/beachball/src/__e2e__/bump.test.ts
- packages/beachball/src/bump/performBump.ts
- packages/beachball/src/help.ts
- packages/beachball/src/options/getCliOptions.ts
- packages/beachball/src/types/BeachballOptions.ts
The current behaviour of `bump` and `publish` implies removal of the change files. This is needed to avoid bumping the same packages multiple times. With the introduction of the [`--since` flag](https://github.com/microsoft/beachball/pull/373) users can select a subset of relevant change files without relying on clean-up. 
Additionally, the rolling release branch flow described in https://github.com/microsoft/beachball/issues/361 implies that master / release branches need to stay as close as possible to each other with the only differences being versions in package.json files and change logs. 
Hence, this PR introduces a new flag to disable the change file removal in `bump` and `publish`. 
Please note, this PR depends on https://github.com/microsoft/beachball/pull/373 :)
> --keep-change-files flag implementation to prevent removing change files

- change/beachball-2020-08-06-17-39-17-arabisho-no-bump-flag-implementation.json
- packages/beachball/src/__e2e__/publishE2E.test.ts
- packages/beachball/src/__e2e__/publishGit.test.ts
- packages/beachball/src/__e2e__/publishRegistry.test.ts
- packages/beachball/src/commands/publish.ts
- packages/beachball/src/help.ts
- packages/beachball/src/options/getDefaultOptions.ts
- packages/beachball/src/publish/publishToRegistry.ts
- packages/beachball/src/types/BeachballOptions.ts
`--no-bump` allows to skip the bump step when invoking the `publish` command. As a side effect, it also implies that publish is not going to have anything to commit or push to the remote repo. Hence, when using `--no-bump` you also get the `--no-push` behaviour. The PR makes necessary changes to the console output and documentation to make that clear to the user.
> `--no-bump` flag implementation

- change/beachball-2020-08-17-15-46-31-sync.json
- packages/beachball/src/commands/sync.ts
- packages/beachball/src/packageManager/listPackageVersions.ts
semver sort of ALL versions might yield prerelease versions being synced down
> Sync needs to use dist-tags for its latest retrieval rather than simple semver sort

- .prettierrc
- change/beachball-2020-09-11-10-57-53-group-disallow.json
- src/__e2e__/packageManager.test.ts
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/__tests__/publish/tagPackages.test.ts
- src/bump/updateRelatedChangeType.ts
- src/changefile/getDisallowedChangeTypes.ts
- src/changefile/promptForChange.ts
- src/fixtures/package.ts
- src/monorepo/infoFromPackageJson.ts
- src/options/getPackageOptions.ts
- src/packageManager/packagePublish.ts
- src/publish/tagPackages.ts
- src/types/PackageInfo.ts
- src/validation/isValidGroupOptions.ts
In a version group, the disallowChangeType must not be specified at the package level. However, the packageInfo options has root options mixed into it. This made the validation of the option to be overly strict. This change preserves which options were set by the package itself. This will allow validations to be more precise.
> Distinguish between combinedOptions vs packageOptions so disallowChangeType check can be done

- change/beachball-2020-09-28-13-54-01-no-loop.json
- src/bump/gatherBumpInfo.ts
- src/changefile/unlinkChangeFiles.ts
In those cases, we should not even consider the dependent changes. In other words, we need to be selective about the "entry" change files. It should also give warning to the users about which files are causing troubles
> Change files that point to a private package is affecting dependent changes

- change/beachball-2020-10-07-15-07-47-bump-specifics.json
- src/__e2e__/publishE2E.test.ts
- src/bump/performBump.ts
- src/fixtures/repository.ts
In the past, the "writePackageJson" overzealously writes over ALL dependencies entries, assuming that the deps entries did not change since the beginning of the build job. This is often not the case. In fact, the most often changed part of a package.json IS the versions of those deps. This, combined with the "merge -X ours" strategy end up with the undesired effect of OVERRIDING the incoming fetched changes. This means that any bumps of unrelated deps (external ones) end up having their bumps reverted.
> Bump specific dependencies instead of the whole thing

- README.md
- change/beachball-2020-10-19-13-52-16-arabisho-sync-by-tag.json
- src/__e2e__/syncE2E.test.ts
- src/commands/sync.ts
- src/help.ts
- src/packageManager/listPackageVersions.ts
Some scenarios require an ability to choose a version tag for syncing packages. By default, beachball uses `latest` and does not allow to choose the distribution tag. This PR adds support for `--tag` in the sync command, as well as adds a couple of E2E tests :)
**cc:** @VincentBailly, @bweggersen
> Update sync command to respect the --tag value

- change/beachball-2020-10-21-14-27-46-arabisho-infer-timestamps.json
- src/__e2e__/bump.test.ts
- src/__e2e__/changelog.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/changefile/promptForChange.ts
- src/types/ChangeInfo.ts
Based on my findings, it seems that beachball doesn't use dates from change files for anything (I might be missing something here). However, timestamps in change files come at a cognitive cost. For example, when working in the long-living branches, the date quickly gets out of sync with the actual changes. The same applies to cherrypicked commits that might include the change files or rebasing the branch.
My initial thoughts were that the date was used to order changelog entries, but `PackageChangeLog` apparently generates its date during the bump and doesn't use the change file date in any way.
This PR removes the date from a changefile. Running tests has not revealed any breaking changes :)
> Remove timestamp from change files

- change/beachball-2020-10-20-15-08-05-arabisho-sync-force.json
- src/__e2e__/syncE2E.test.ts
- src/commands/sync.ts
- src/help.ts
- src/options/getCliOptions.ts
- src/types/BeachballOptions.ts
This PR implements the `--force` flag for the sync command, which allows us to skip the version comparison and use the version in the registry as is.
**cc:** @VincentBailly, @bweggersen
> Implements the --force flag for sync

- change/beachball-c8f63b87-9c78-426d-84b9-3fa7182653c2.json
- src/commands/sync.ts
- src/packageManager/listPackageVersions.ts
This PR enables the sync command to use the `--token` argument for authentication against the registry.
> Respect --token argument in the sync command

- change/beachball-d030ff29-357f-4404-be5b-0b800e7582da.json
- src/options/getCliOptions.ts
- src/types/BeachballOptions.ts
The `disallowed-change-types` option allows the user to specify the `disallowedChangeTypes` as CLI args without adding the `beachball` config. It is especially useful on CI, where different policies can specify `disallowedChangeTypes` without changing the beachball config on the disk.
> Expose disallowed-change-types as a CLI option

- change/beachball-b0d9adf7-3d09-4bf0-92b4-9a1d6b5a55fc.json
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/syncE2E.test.ts
- src/changefile/promptForChange.ts
- src/help.ts
- src/options/getCliOptions.ts
- src/types/BeachballOptions.ts
- src/validation/validate.ts
This PR:
* Fixes a bug: when the `--type` argument is passed without `--message`, the `response.type` always ends-up being `undefined`. This happens because the list of questions does not include the change type prompt, anticipating the value to be available from `options.type`, but the `response.type` receives undefined as the message prompt overrides it. 
* Adds a new CLI argument `--dependent-change-type` that allows overriding the default change type calculated for change files. This flag is handy when the PR author knows what kind of change (other than `none` or `patch`) is anticipated for dependent packages. For example, if package C in graph A <- B <- C receives a new pre-release version 1.0.0-2, I would want B and C also to receive a pre-release bump.
> Parameterise dependentChangeType and fix a bug of the --type arg being ineffective

- change/beachball-fe8092a1-3abd-42fa-84e5-39263d79e0ad.json
- src/__e2e__/validation.test.ts
- src/changefile/readChangeFiles.ts
- src/fixtures/repository.ts
- src/git/index.ts
- src/help.ts
- src/options/getCliOptions.ts
- src/types/BeachballOptions.ts
- src/validation/areChangeFilesDeleted.ts
- src/validation/validate.ts
When `beachball` is invoked together with the `--disallow-deleted-change-files` flag, beachball will verify that no change files were deleted by inspecting the diff between head and `--branch`.
> Implement the 'disallow-deleted-change-files' flag

- change/beachball-5d642d94-42cc-4a0b-8404-359bfb1dfe40.json
- src/git/index.ts
In repositories with massive git history, a call to `git log` without capping the commit count leads to a process crash. This PR caps the git log output by 100 commits.
> Prevent git process from crashing with enobufs when collecting git messages

- change/beachball-e88a3f18-8aca-4ca2-a348-d8f0c2a9ff71.json
- docs/cli/options.md
- src/__e2e__/bump.test.ts
- src/bump/bumpInPlace.ts
- src/bump/bumpPackageInfoVersion.ts
- src/help.ts
- src/types/BeachballOptions.ts
SemVer specification allows `prerelease` version to be a string/number combination. For example: `1.0.0-beta.5`, where `beta.5` is a prerelease version. Unfortunately, beachball does not give a user control over the prerelease prefix. This PR addresses this at the level of the `bump` command. 
This is extremely useful if you want to scope versions to avoid conflicts. For example, `1.0.0-beta.2` and `1.0.0-alpha.2` are two different versions. Without `--prerelease-prefix` option, beachball will be calculating the same version (`1.0.0-2` and `1.0.0-2`) for two packages that have different contents.
> Add a CLI argument that allows to specify a prerelease prefix

- change/beachball-28c0f2c4-6394-4dfc-94d5-0c8854742e09.json
- src/__e2e__/__snapshots__/changelog.test.ts.snap
- src/__e2e__/changelog.test.ts
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/bump/bumpInPlace.ts
- src/bump/bumpPackageInfoVersion.ts
- src/bump/gatherBumpInfo.ts
- src/bump/performBump.ts
- src/bump/updateRelatedChangeType.ts
- src/changefile/getPackageChangeTypes.ts
- src/changelog/getPackageChangelogs.ts
- src/changelog/writeChangelog.ts
- src/publish/shouldPublishPackage.ts
- src/publish/tagPackages.ts
- src/types/BumpInfo.ts
Currently, beachball generates changelogs only for packages that are described in change files. Dependent packages, however, do not receive new changelog entries, even though their versions get bumped. 
This PR enables beachball to rollup a changelog entry to dependents, such as: `Bump ${package} to v${version}` making it obvious what has caused the version bump.
> Rolling-up the changelogs to dependents

- src/changefile/promptForChange.ts
This commit handles edge case for properly setting `response.type` in `promptForChange` in a situation when `options.type` is `undefined` or `null` **and** there is only one viable default `ChangeType` option (`'none'`) in which case the type prompt won't be shown, and we fall back to `'none'` by default.
Prior to this change, since `options.type` would be left `undefined` and the type prompt not shown, the CLI would incorrectly exit with "Prompt response contains invalid change type" without any other hint to the user.
For more context, this problem emerged when we were adding a new package to the [microsoft/fluentui](https://github.com/microsoft/fluentui) repo: microsoft/fluentui#16458.
---
EDIT:
After offline discussion with @ecraig12345, we agreed it would make sense to emit a warning …
> Fix setting response.type in promptForChange

- README.md
- change/beachball-298836ae-681c-4d08-8bb6-cc76f7759dac.json
- src/__e2e__/config.test.ts
- src/cli.ts
- src/options/getCliOptions.ts
- src/options/getOptions.ts
- src/options/getPackageOptions.ts
- src/options/getRootOptions.ts
- src/types/BeachballOptions.ts
Automated testing for this change was a bit tricky. To make options code more testable, we allowing injecting argv instead of grabbing from the process, which we should not mutate, and may have flags we don't want. E.g. E2ETest will run jest with a `--config` flag we don't want in our tests.
This exposed some issues where `getCliOptions` was accidentally trimming bits off of process.argv, and we needed to change the CLI options cache to allow different values of argv to have different results. We do this by special casing the cache to only cache when the input is process.argv, which should be immutable and will be the only option used in production code.
> Allow passing --config to specify config file

- src/changefile/promptForChange.ts
The current hints for patch and minor changes use different language to tell users that they should only have backwards compatible changes. This change unifies the language, going for the least complicated phrasing.
> Remove the double negative in patch change hint 

- src/__e2e__/change.test.ts
- src/changefile/writeChangeFiles.ts
- src/commands/change.ts
- src/git/index.ts
- src/help.ts
- src/options/getCliOptions.ts
- src/types/BeachballOptions.ts
This commit adds `--no-commit` flag which only affects `beachball change` command. With this flag set, the change files generated with `beachball change` will only be staged for commit in git, but the commit will have to be done manually by the caller of `beachball`. The defaults stay the same, i.e., by default we still stage and autocommit the generated change files for the user with message 'Change file'.
Suggested usage for only staging change files:
```
beachball change --no-commit
```
This addition is motivated by a few of us working on [microsoft/fluentui](https://github.com/microsoft/fluentui) constantly finding ourselves uncommitting the change files and then squashing them with the actual changes to the codebase.
> feat(change): add --no-commit flag to CLI

- change/beachball-8b85a3d0-0204-430c-ae46-b75a6902d9f4.json
- src/changefile/promptForChange.ts
- src/publish/validatePackageDependencies.ts
- src/validation/validate.ts
In Fluent UI we've repeatedly had issues where someone adds a new package which accidentally has `"private": true` set in its package.json, adds the new package as a dep of a published package, and this isn't detected until publishing fails.
Fix is to update `beachball check` to run the same validation logic that's used before publishing to catch these types of errors.
> check: Add validation of published package deps

- change/beachball-e50c5d70-a427-41d3-9181-a65cbb99530e.json
- src/__e2e__/publishE2E.test.ts
- src/fixtures/monorepo.ts
- src/publish/publishToRegistry.ts
- src/types/BeachballOptions.ts
Add postpublish hook used to modify files after publishing, or to kick off other processes. One concrete example is to update lock files, which currently don't get updated (using npm)--see #482.
Fixes #488 
Fixes #482
> Add postpublish hook

- change/beachball-9ec2303e-6777-4b37-9a83-a17fe56954a1.json
- src/monorepo/getPackageInfos.ts
Using the workspace-tools getWorkspaces() to get packageInfo rather than the listAllTrackedFiles which could be error prone if there are package.json checked in but not in a workspace.
> Use getWorkspaces() rather than listAllTrackedFiles() to get packages.

- change/beachball-226ed93e-ad37-4475-8be5-5a684c13c8a4.json
- src/commands/canary.ts
This change updates the canary cli command to respect --no-publish
**Behavior before**
```
D:\repos\beachball [jaburnsi/fixNoPublishCanary ≡ +0 ~1 -0 !]> node ./lib/cli.js canary --canary-name canaryname --tag canarytag --no-publish
Validating no private package among package dependencies OK!
Validating package version - beachball@1.53.2-canaryname.0 OK!
Validating no private package among package dependencies OK!
Publishing - beachball@1.53.2-canaryname.0 with tag canarytag.
publish command: publish --registry https://registry.npmjs.org/ --tag canarytag --loglevel warn
```
**Behavior after**
```
D:\repos\beachball [jaburnsi/fixNoPublishCanary]> node ./lib/cli.js canary --canary-name canaryname --tag canarytag --no-publish
Validating no private package among package dependencies OK! …
```
> Fix: update canary cli command to respect --no-publish flag 

- change/beachball-bfdc4803-018a-4049-8780-3efffac42b81.json
- package.json
- src/fixtures/registry.ts
- src/packageManager/npm.ts
- yarn.lock
Dependency up now that node 10 is almost EOL'ed.
* node engine is now at 12.0.0+
* added @types/node@^12.0.0
* fixed typing errors (execa.Options not compatible?)
> MAJOR BUMP to 2.0: breaking change is to move to node 12.0+

- change/beachball-63d5ee60-97e9-4c05-a1d1-66d17a3d7747.json
- package.json
- yarn.lock
0.14 provides a smaller list of commit messages to select for our change
description, as it just returns commits on our branch that are not in
the target branch.
> Bump workspace tools

- change/beachball-b9f81072-b73d-4dae-8e88-092f9f64654e.json
- src/bump/updateRelatedChangeType.ts
- src/types/ChangeInfo.ts
- src/validation/isValidDependantChangeType.ts
- src/validation/validate.ts
Validate the dependentChangeType field in the changefile.
Validations include: 
- Check if it is a valid change type.
- Check if it is not a disallowed change type (if specified)
> Validate the dependentChangeType field

- change/beachball-a9607dc7-0c16-4883-a0d1-77911df68c28.json
- src/__e2e__/changelog.test.ts
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/__tests__/publish/tagPackages.test.ts
- src/__tests__/publish/validatePackageDependencies.test.ts
- src/bump/bumpInPlace.ts
- src/bump/bumpPackageInfoVersion.ts
- src/bump/gatherBumpInfo.ts
- src/bump/performBump.ts
- src/bump/updateRelatedChangeType.ts
- src/changefile/getPackageChangeTypes.ts
- src/changefile/readChangeFiles.ts
- src/changelog/getPackageChangelogs.ts
- src/changelog/writeChangelog.ts
- src/commands/publish.ts
- src/publish/shouldPublishPackage.ts
- src/publish/tagPackages.ts
- src/types/BumpInfo.ts
Included are two major changes to speed up beachball tremendously:
1. rewrites the beachball update related change types internal algorithm to be a lot faster
2. no hash calculation per change file
I've used the e2e tests as well as hand tested to validate the change. I'm reasonably confident the results are the same as before. There's no behavior changes except for the fact that it is faster.
> No hash in change & rewritten updateRelatedChangeTypes

- change/beachball-701b536a-cdf6-499c-b60b-36c6dfb7545b.json
- src/__e2e__/__snapshots__/changelog.test.ts.snap
- src/__e2e__/changelog.test.ts
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/__tests__/changelog/getPackageChangelogs.test.ts
- src/bump/bumpInPlace.ts
- src/bump/performBump.ts
- src/bump/updateRelatedChangeType.ts
- src/changelog/getPackageChangelogs.ts
- src/changelog/writeChangelog.ts
Fixes #553 
1. getPackageChangelogs was taking in the incorrect changeinfo for its job - changed back to dependentChangeInfos + the changeFileChangeInfos
2. fixes the updateRelatedChangeTypes to create  baseChangeInfo based on changeFileChangeInfos.get(changeFile) rather than package name
3. added some test cases for the updated code
> Fixes changelog comments being overridden by the auto-generated dependent bump comments

- src/changefile/writeChangeFiles.ts
The status message says:
> git commited these change files: <list>
In fact, it should say "committed".
> chore: Fix a typo in the status message

- change/beachball-3d0b6a3d-44a8-4046-aaa3-7e338d0ec7e6.json
- src/changefile/promptForChange.ts
- src/types/ChangeFilePrompt.ts
Currently the beachball allows to specify a custom schema for the changelog(s) at the repository level. So, we cannot have a custom schema at the package level.
This PR introduces more flexibility in terms of defining a custom schema for the changelog, by allowing developers to specify a custom schema at the package level.
For example - 
Currently in the beachball config file we can have - 
`
changeFilePrompt: {
changePrompt: prompt => {}
}
`
will be now like - 
`
changeFilePrompt: {
changePrompt: (prompt, packageName) => {
// logic to return the schema based on the packageName
}
}
`
> Option to specify Custom changelog at the package level

- change/beachball-7c2b234c-3dbf-430f-956b-a4bdb4fdacfa.json
- src/changelog/getPackageChangelogs.ts
- src/types/ChangeInfo.ts
Currently, the consumers can specify a custom schema in the beachball config file (`
changeFilePrompt: {
changePrompt: prompt => {}
}
`) which gets used for creating the individual change files. But when the CHANGELOG.json files are updated not all the fields of the change file gets included in the update written to the CHANGELOG.json file. Due to this the custom schema fields although being part of the generated change files are not included in the CHANGELOG.json file.
This PR introduces the fix to include all the custom schema fields present in the change file to be written to the CHANGELOG.json file when the CHANGELOG.json file is updated.
Fixes #549
> Fix for handling of custom schema while updating the CHANGELOG.json file

- change/beachball-08413465-8d24-4f5a-aeba-7ec04112dc1c.json
- src/__tests__/publish/performPublishConfigOverrides.test.ts
- src/publish/performPublishConfigOverrides.ts
This adds logic to fallback to values defined on the root of `package.json` when they are not defined within `publishConfigs`. 
---
I ran into a situation where I need a `publishConfig` to specify a private registry we are publishing to. We have our `main` and `files` options specified on the root of the `package.json`. Our `package.json` looked something like this:
```json
{
"name": "@my-scope/my-package",
"version": "1.0.0",
"description": "",
"main": "dist/index.js",
"files": ["dist"],
"publishConfig": {
"registry": "https://registry.my-private-npm.com"
},
"scripts": {},
"dependencies": {},
"devDependencies": {},
}
```
Using `beachball` in its current form, my published package was missing `main` and `files` from the `package.json` file. This caused upstream dependencies to fail when …
> Add fallback logic for publishConfig values

- change/beachball-446b7dbb-7400-46bf-ba2a-f539ef4ccdb6.json
- src/__e2e__/changelog.test.ts
- src/__e2e__/monorepo/getScopedPackages.test.ts
- src/__e2e__/multiMonorepo.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/validation.test.ts
- src/bump/gatherBumpInfo.ts
- src/changefile/getChangedPackages.ts
- src/changefile/getDisallowedChangeTypes.ts
- src/changefile/promptForChange.ts
- src/changefile/readChangeFiles.ts
- src/commands/bump.ts
- src/commands/canary.ts
- src/commands/publish.ts
- src/commands/sync.ts
- src/monorepo/getAllPackages.ts
- src/monorepo/getPackageInfos.ts
- src/monorepo/getScopedPackages.ts
- src/types/ChangeInfo.ts
- src/validation/isChangeFileNeeded.ts
- src/validation/isValidPackageName.ts
- src/validation/validate.ts
I noticed while cleaning up the validation code that `getPackageInfos()` (which reads all packages from the filesystem) was unnecessarily called multiple times within the same method, instead of being passed around. So I added it as a parameter to several utility functions and passed it through from the appropriate higher-level functions. 
This also caused a bunch of churn in tests for the utilities, since I had to add explicit calls to `getPackageInfos`.
> Reduce number of times getPackageInfos is called

- change/beachball-446b7dbb-7400-46bf-ba2a-f539ef4ccdb8.json
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/bump/updateRelatedChangeType.ts
- src/monorepo/getPackageGroups.ts
- src/types/PackageInfo.ts
- src/validation/validate.ts
`PackageInfo.group` was being set as a side effect in `getPackageGroups`, and only read in `updateRelatedChangeType`. This PR removes the property and the side effect, and determines the group within `updateRelatedChangeType` in a different way using information already available.
This is technically a breaking change due to removal of the property, but since it's optional and only set (and hopefully only read) internally, it's unlikely to cause issues in practice.
(I also added back a line in `validate.ts` which was accidentally removed in the previous change.)
> Remove PackageInfo.group side effect

- change/beachball-c9ad3600-06b8-481e-a904-fbd622de09e1.json
- jest.config.js
- jest.e2e.js
- src/__e2e__/__snapshots__/changelog.test.ts.snap
- src/__e2e__/changelog.test.ts
- src/changefile/readChangeFiles.ts
- src/types/BeachballOptions.ts
This PR introduces an option to specify any custom transform method for the change files. It can be used to add more information to the change files which might not be present at the time of their generation. 
The consumer can have the following beachball config file to use this functionality - 
```
{
...
transform: {
changeFiles: (changeFile, path) => {
// Add or Edit the information in the changeFile
return changeFile;
};
}
...
}
```
> Option to specify custom transform method for the change files

- change/beachball-ee61e91a-12c5-4cf6-b6a1-198ef94cfa65.json
- src/__e2e__/__snapshots__/changelog.test.ts.snap
- src/__e2e__/bump.test.ts
- src/__e2e__/changelog.test.ts
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/__tests__/changelog/getPackageChangelogs.test.ts
- src/__tests__/publish/tagPackages.test.ts
- src/__tests__/publish/validatePackageDependencies.test.ts
- src/bump/bumpInPlace.ts
- src/bump/bumpPackageInfoVersion.ts
- src/bump/gatherBumpInfo.ts
- src/bump/performBump.ts
- src/bump/setDependentVersions.ts
- src/bump/updateRelatedChangeType.ts
- src/changefile/getPackageChangeTypes.ts
- src/changelog/getPackageChangelogs.ts
- src/changelog/renderPackageChangelog.ts
- src/changelog/writeChangelog.ts
- src/commands/sync.ts
- src/publish/shouldPublishPackage.ts
- src/publish/tagPackages.ts
- src/types/BumpInfo.ts
This is a change that is long in coming where we get rid of data structures internally that are no longer needed. Sticking to the principle that we keep the state as close to what is needed rather than just having a free-for-all style in the BumpInfo.
This fixes #596 with the updateRelatedChangeType changes. The grouped version was not set correctly before, and this addresses that issue as well.
Note: the snapshots are updated because the changeinfo that was created before was "fake" - and now we actually teach the changelog generation to understand dep bumps with a new "dependentChangedBy" field in BumpInfo. Since the changelog now doesn't take in faked changeinfo objects for dependent bumps, we actually will see the existing versions in these changelog tests.
> Fix changelog generation for dependent and fixes version group bumping - adding more tests to validate the changelog

- change/beachball-4b52a6da-b855-4d0c-a7ae-89199ea7a03f.json
- src/types/BeachballOptions.ts
The `scope` CLI option, can be used in the configuration file regardless
of it being a cli specific option.
Adds `scope` to the `RepoOptions` type so that it can be used in the
config file as a part of `BeachballConfig`
Also improves the options types by making `CliOptions` extend shared
`RepoOptions`. Also sorts the options for easier readability in the future.
> chore(BeachballOptions): Move `scope` to `RepoOptions` type

- change/change-chatty-cloths-develop.json
- docs/overview/configuration.md
- package.json
- src/__e2e__/__snapshots__/changelog.test.ts.snap
- src/__e2e__/change.test.ts
- src/__e2e__/changelog.test.ts
- src/changefile/getChangedPackages.ts
- src/changefile/promptForChange.ts
- src/changefile/readChangeFiles.ts
- src/changefile/writeChangeFiles.ts
- src/commands/change.ts
- src/types/BeachballOptions.ts
- src/types/ChangeInfo.ts
- src/validation/validate.ts
- yarn.lock
In large repos when you're changing a bunch of packages at once, it can be kind of expensive to dump a bunch of JSON files into a single folder.
It's easy enough to just group the change files into single files expressing multiple packages per file.
Essentially, there would be a new `multiPackageChanges` option that would generate change files like...
```json
{
"changes": [{
"packageName": "beachball",
"type": "minor",
"dependentChangeType": "patch",
"email": "jcreamer@microsoft.com",
"comment": "support multiple changes per changefile"
}]
}
```
And there's a bit of confusion on my end as to why each `ChangeInfo` needs its own `comment` as I think that `comment` field is generated from the `yarn change` command? So perhaps we can bubble that `comment` field up into the `summary` as seen …
> support multiple packages per changefile

- change/beachball-131dbea8-982d-4330-9638-931d0bed08ec.json
- docs/cli/options.md
- src/bump/bumpInPlace.ts
- src/bump/setDependentVersions.ts
- src/bump/setDependentsInBumpInfo.ts
- src/commands/canary.ts
- src/commands/sync.ts
- src/help.ts
- src/types/BeachballOptions.ts
We've had several incidents where Beachball was trying to bump packages that were completely unrelated to the current changes and failing. Having this extra output would at least make it easier for us to see where Beachball is tripping.
Related build logs:
- https://github.com/microsoft/rnx-kit/runs/3266347469?check_suite_focus=true
- https://github.com/microsoft/rnx-kit/runs/3338523522?check_suite_focus=true
Example output:
```
$ beachball publish --bump-deps --verbose
Skipping bumping private package "@rnx-kit/test-app"
@rnx-kit/cli needs to be bumped because @rnx-kit/console ^1.0.1 -> ^1.0.2
@rnx-kit/metro-config needs to be bumped because @rnx-kit/babel-preset-metro-react-native ^1.0.3 -> ^1.0.4
Validating no private package among package dependencies OK!
```
> Add --verbose flag for making debugging easier

- change/beachball-4e5b7fbd-6a4c-4994-b038-9c0cf2b507dd.json
- src/__e2e__/bump.test.ts
- src/bump/performBump.ts
- src/types/BeachballOptions.ts
These hooks allow for mutating the filesystem during a bump. E.g. to allow stamping files apart from package.json, to be checked in and added to the package.
Validated by adding E2E tests.
> Add Bump Hooks

- change/beachball-38cfe027-5bee-45bf-b7f8-7f044ca8f60a.json
- src/__tests__/changelog/getPackageChangelogs.test.ts
- src/changelog/getPackageChangelogs.ts
Addresses issue #480, which was a un-documented behavior introduced in version 1.49.0 from the "Roll-up the changelogs to dependents" feature.
> Prevent generation of changelog files for private packages

- README.md
- change/beachball-b87a5254-ef04-4728-8e25-f5db13d0b15f.json
- src/help.ts
Now that beachball picks up the default branch which is now usually 'main' rather than the older 'master'.
This change updates the docs to reflect that.
> Update help and readme to not refer to 'master' branch

- README.md
- change/beachball-e1c73f61-4a19-45ee-a264-2d1a42932db7.json
- src/help.ts
`--help` and the readme mention a `changelog` command that doesn't exist. Remove this.
Fixes #634
> Remove docs for nonexistent changelog command

- change/beachball-a33d8be0-b765-47ac-a8c8-c94d80374735.json
- src/__e2e__/bump.test.ts
- src/bump/bumpPackageInfoVersion.ts
This PR is a re-up of #633 by @PorterNan, which fixes the failing e2e test.
From the original PR:
> This PR is to fix the logic of prerelease tag not working.
According to api doc from semver, prerelease bump should be like this:
https://www.npmjs.com/package/semver#:~:text=semver.inc(%271.2.3%27%2C%20%27prerelease%27%2C%20%27beta%27)
> 
> This change will allow beachball to call semver using 'prerelease' parameter to do a correct prerelease bump
> Update the api call for prerelease to semver

- change/beachball-3e377ae5-505a-4a93-ac31-b03334e67971.json
- src/bump/performBump.ts
- src/commands/sync.ts
If the package manager is detected to be npm (as determined by presence of `package-lock.json`), beachball should run `npm install --package-lock-only` to update `package-lock.json` after bumping or syncing.
I currently have this new behavior happening automatically rather than under a flag, because arguably it's something beachball should have been doing all along (the only reason it didn't was because the maintainers were primarily using beachball with yarn). If that seems risky, I could add a flag, but if we do that it should definitely become the default behavior in a future major version.
Fixes #525
> Update package-lock.json after bumping packages

- change/beachball-2222cbfe-8464-46da-b620-d7fab0a21dcd.json
- src/packageManager/listPackageVersions.ts
> fix: check npm show stdout for valid (non-empty) output

- change/beachball-e8e41d79-466d-48e2-bc0d-91615011c641.json
- package.json
- src/bump/performBump.ts
- src/changefile/getChangedPackages.ts
- src/commands/init.ts
- src/monorepo/getPackageInfos.ts
- src/options/getCliOptions.ts
- src/paths.ts
- src/validation/areChangeFilesDeleted.ts
- src/validation/isGitAvailable.ts
- yarn.lock
Beachball has a file with various path utilities which are now redundant with utilities provided by workspace-tools (probably because they were copied from beachball into workspace-tools). This PR updates it to use the workspace-tools versions instead.
The only path utility I decided to keep in beachball is `getChangePath`, because that's definitely specific to beachball and not used elsewhere. (It exists in workspace-tools currently, but I have a PR https://github.com/microsoft/workspace-tools/pull/115 to remove it since it's really not appropriate for that package.)
Removal of the utilities is technically not a breaking change because they're not exported. If anybody was using the utilities via deep imports, they can switch to using the workspace-tools versions.
> Use path utilities from workspace-tools

- change/beachball-6cc28bf0-06b2-4bc4-b9bf-c6938e814c51.json
- package.json
- yarn.lock
git-url-parse@11.1.2 has a vulnerability as described [here](https://snyk.io/test/npm/git-url-parse/11.1.2), and we can mitigate it by upgrading to 12.0.0.
This should resolve #682.
> Bump git-url-parse to 12.0.0

- change/beachball-89771895-0bcc-432c-8657-2564c7c4d05e.json
- package.json
- src/options/getCliOptions.ts
- src/options/getRepoOptions.ts
- yarn.lock
Pick up https://github.com/microsoft/workspace-tools/pull/34 to improve detection of which remote to compare against. This should result in more reliable detection by default in most cases. 
If a branch with remote isn't specified in any options, and there's no `repository` key in the repo/workspace root `package.json`, a message will be logged encouraging adding it. There will also be more logs about the remote choice if `--verbose` is enabled.
Fixes #490
> Update workspace-tools to improve remote detection

- change/beachball-8301b1dc-df80-4dee-817a-ce1a0c97f705.json
- package.json
- yarn.lock
Typescript 4.3 was released in May 2021 and is required by `ts-jest` 28 and probably an increasing number of other tools (also the latest `@types/jest` needs 4.1+). Especially since beachball is a command line tool where the primary use case doesn't involve types at all, upgrading to 4.3 seems fairly safe at this point.
> Update typescript to 4.3

- change/beachball-a657dddd-867a-412e-a137-df458a16f2c0.json
- src/__e2e__/bump.test.ts
- src/__e2e__/change.test.ts
- src/__e2e__/changelog.test.ts
- src/__e2e__/multiMonorepo.test.ts
- src/__e2e__/packageManager.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/syncE2E.test.ts
- src/__e2e__/validation.test.ts
- src/__fixtures__/mockLogs.ts
- src/__tests__/changelog/renderChangelog.test.ts
- src/__tests__/publish/performPublishOverrides.test.ts
- src/__tests__/publish/tagPackages.test.ts
- src/__tests__/publish/validatePackageDependencies.test.ts
- src/publish/validatePackageDependencies.ts
For tests involving code which logs to the console, it can be hard to find the actual errors due to all the random logs. 
This PR adds a helper `initMockLogs()` which mocks `console.log`, `console.warn`, and `console.error`, and uses it in relevant tests. If you do want to see the console logs, you can pass `VERBOSE=1` as an environment variable.
> Mock logs in tests

- .github/workflows/pr.yml
- change/beachball-c53bf487-69d7-42d5-a37b-a4cd0a3e2003.json
- src/__e2e__/packageManager.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/syncE2E.test.ts
- src/bump/performBump.ts
- src/commands/init.ts
- src/packageManager/npm.ts
- src/packageManager/packagePublish.ts
- src/publish/displayManualRecovery.ts
- src/publish/publishToRegistry.ts
- src/publish/validatePackageVersions.ts
While debugging the issues with verdaccio that turned out to be due to npm 8 (somehow), I noticed that handling of logs during publishing could use some improvement. 
This PR improves the logging and some related things:
- Update the logs to be clearer in places
- Specifically check for auth errors during publishing, and doesn't retry if found (retries won't help in that case). Also don't try to publish any of the other packages since they'll presumably have the same issue.
- Reduce the number of separate `console.log`/`console.error` calls, mainly for convenient reading while testing
- Fix the types of the npm helper method
- Use the npm helper method everywhere (a couple places were still using `spawnSync` directly)
> Improve auth error handling and other logs during publishing

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .vscode/settings.json
- change/beachball-08dc36b3-0449-4b5c-ad64-919679dc19ac.json
- package.json
- src/__fixtures__/registry.ts
- src/__fixtures__/verdaccio.js
- src/__fixtures__/verdaccioUser.js
- tsconfig.json
- yarn.lock
Any e2e tests involving publishing to a mock verdaccio registry were failing for me locally, and I eventually figured out this was somehow due to a difference in behavior between npm 6 and 7/8: something about the newer versions messes up verdaccio's handling of anonymous access for publishing (even when it's enabled in the verdaccio config). 
Since I couldn't figure out the underlying issue and how to fix it properly (not for lack of trying...), I added a step in the mock registry setup to log in as a fake user. This works on both npm 6 and 8. (The `verdaccio-auth-memory` package is used to configure the fake user credentials.)
I also updated the PR build to test against npm 6 and 8, and updated the release build to specifically use npm 8.
Another issue I was sometimes having locally is …
> Fix issue with publishing tests in npm 8

- src/__fixtures__/tmpdir.ts
On Mac, the `tmp` utility returns paths like `/var/...` which is actually a symlink to `/private/var/...`. Mixing the symlink path returned there with real paths used in other places causes test failures/inconsistency in any tests involving functions that use relative paths.
The easiest workaround is to fix the wrapping `tmpdir` utility to return the real path.
> Make test tmpdir utility return real paths

- change/beachball-ab2abe4c-7638-43fd-94ff-115d684717bf.json
- src/changefile/getChangedPackages.ts
#693 introduced an infinite loop when trying to match a modified file to its corresponding package, because `path.posix.normalize` wasn't replacing backslashes with forward slashes. This PR should fix it by using standard `path.normalize` on everything.
(Thankfully a version with the break was not released, and this fix will go in before the release.)
> Fix calculation of changed packages on Windows

- change/beachball-a48ce55c-e925-4c80-b1ad-be124a5662c9.json
- tsconfig.json
Main motivation for this is that async/await doesn't need to be transpiled in ES2019, so it's easier to debug. 
I noticed this because I was trying to debug something and a lot of important frames were marked as "skipped by smartStep," which the [VS Code docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_smart-stepping) mention can happen due to transpiled async/await.
> Use ES2019 output (compatible with Node 12+)

- change/beachball-42aa9898-e458-4620-84d6-6ef87ec4a32f.json
- src/__e2e__/__snapshots__/changelog.test.ts.snap
- src/__e2e__/changelog.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__fixtures__/mockLogs.ts
- src/bump/gatherBumpInfo.ts
- src/changefile/readChangeFiles.ts
- src/changelog/writeChangelog.ts
If a package had only invalid change files (packages that were private or didn't exist), beachball would start the publish process but then fail partway through because there was nothing to commit. `getBumpInfo` had attempted to filter out those files, but by that point it was too late because the publish process had already started.
This PR fixes the issue at the root by modifying `readChangeFiles` to exclude (and warn about) any change files from private or nonexistent packages. 
Fixes #597
> Exit publishing early if only invalid change files are present

- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/syncE2E.test.ts
Some of the E2E tests had complete beachball options objects repeated in every test, which made the file harder to read and made it harder to see which options were important to the test.
This PR adds helpers for generating the shared options in each test, deferring to `getDefaultOptions()` where possible, and allowing per-test overrides.
It also starts removing literal references to `master` as the default branch name, to make things more portable across git versions and eventually migrate towards using `main`. (There will be more work on this in the future.)
> Add helpers for generating beachball options in tests

- .github/workflows/pr.yml
- .github/workflows/release.yml
#735 added e2e test runs against both npm 6 and 8. Since the e2e tests are the slowest part of the build, this also slows down the build overall. 
Switching to complete parallel runs will make the overall build faster again. (If this causes resource constraint issues in the future, we could go back to the previous approach.)
I also broke out test:unit and test:e2e into separate steps to make it clearer what's running/failed and the timings.
> Do npm 6 and 8 builds in parallel

- src/__e2e__/bump.test.ts
- src/__e2e__/change.test.ts
- src/__e2e__/changelog.test.ts
- src/__e2e__/multiMonorepo.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/validation.test.ts
- src/__fixtures__/changeFiles.ts
Add `generateChangeFiles` and `readChangeFiles` helpers to reduce the amount of redundant code in tests and make them easier to read. 
This is especially impactful for the bump and publishE2E tests due to overall number and complexity of the tests.
> Add test helpers for generating and reading change files

- change/beachball-b30f1e87-c619-41f6-a73b-8d82f13228c0.json
- src/__e2e__/publishE2E.test.ts
- yarn.lock
Pick up https://github.com/microsoft/workspace-tools/pull/167 and call the new `clearGitObservers` method in the `publishE2E` test.
> Update workspace-tools and clean up git observers in tests

- src/__e2e__/packagePublish.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__fixtures__/npmShow.ts
Add a helper to reduce boilerplate and potential errors around running `npm show` in tests.
Switch to mostly testing the returned object using [`expect(...).toMatchObject`](https://jestjs.io/docs/expect#tomatchobjectobject) because it's easier to read. Doing this also revealed a couple interesting things about the test results, such as the fact that publishing a brand new package will always create a `latest` tag in addition to any specified tag.
In the same tests, check the success of `packagePublish` using [`expect.objectContaining`](https://jestjs.io/docs/expect#expectobjectcontainingobject) instead of just looking at the `success` property. This causes any errors logged by npm to show up in the build output for debugging (otherwise it's impossible see what went wrong).
> Add helper for running "npm show" in tests

- src/__e2e__/bump.test.ts
- src/__e2e__/change.test.ts
- src/__e2e__/changelog.test.ts
- src/__e2e__/config.test.ts
- src/__e2e__/getChangedPackages.test.ts
- src/__e2e__/monorepo/getScopedPackages.test.ts
- src/__e2e__/multiMonorepo.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/syncE2E.test.ts
- src/__e2e__/validation.test.ts
- src/__fixtures__/monorepo.ts
- src/__fixtures__/multiMonorepo.ts
- src/__fixtures__/repository.ts
This change simplifies various aspects of repository fixture setup and internals, to reduce boilerplate in tests.
Instead of having separate `repositoryFactory.create()` and `repository.init()` methods, it's simpler to just have the constructor do the initialization, because construction and create/init happened 1:1 right after each other except in one test.
Introduce an abstract class `BaseRepositoryFactory` which handles all the basic repo setup (which was identical between the different factories) and has an abstract method for creating the actual fixture files.
Add a helper method `repository.git()` for running git operations on a repository in the correct `cwd`, and throwing if the operation fails. This will also reduce boilerplate once it's more widely adopted in other tests.
> Simplify repository fixture setup

- src/__e2e__/bump.test.ts
- src/__e2e__/change.test.ts
- src/__e2e__/changelog.test.ts
- src/__e2e__/getChangedPackages.test.ts
- src/__e2e__/multiMonorepo.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishGit.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/validation.test.ts
- src/__fixtures__/changelog.ts
- src/__fixtures__/repository.ts
Instead of calling `git()` directly in tests, add helper methods on `Repository` to run most of the operations and process the output. 
Centralizing git operations like this reduces boilerplate and makes the tests easier to read.
> Add helper methods for git operations in tests

- change/beachball-0b973948-5e88-4403-9731-6fbb9b375e4a.json
- src/monorepo/getPackageInfos.ts
In a monorepo with multiple workspaces, it's theoretically possible that a package name could be reused across the different workspace roots (this happened with the multi-workspace fixture until I recently added scopes to the package names). This creates problems in `getPackageInfos` because the packages are stored in an object indexed by package name, and prior to this PR, it would silently overwrite the first package with the second. 
This PR makes beachball exit with an error instead. Arguably it could do just a console warning instead, but a package being entirely ignored (due to the duplicate name) is a bad enough situation that I think it's better to fail loudly and make the user fix it.
> Error on duplicate package names

- package.json
- src/__e2e__/packagePublish.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/syncE2E.test.ts
- src/__fixtures__/registry.ts
The E2E tests were configured to run in series due to race conditions with getting ports for the fake registry. The problem with this is that the E2E tests are slow in general (due to amount of filesystem and local-network operations), so running them in series makes them very slow, particularly on Windows PR builds.
This PR adds logic to try a different range of ports for each test file which uses the fake registry. One way to do that would have been to have each test pass a start port to the constructor, but that could lead to intermittent failures if someone copy-pastes a test in the future. So instead I based the port ranges on array indices for a hardcoded list of test filenames. (That approach could cause very minor annoyance if adding or renaming test files in the future, but the …
> Run E2E tests in parallel

- .github/workflows/pr.yml
- src/__fixtures__/repository.ts
- src/__fixtures__/repositoryFactory.ts
- src/__fixtures__/tmpdir.ts
Build on Ubuntu and Windows in PRs to reduce the chance of breaking something.
This required adding workarounds for different possible ways of writing the same temp path on Windows.
> Add Windows PR build

- src/__e2e__/publishE2E.test.ts
- src/publish/bumpAndPush.ts
- src/publish/mergePublishBranch.ts
- src/types/BeachballOptions.ts
Adds a precommit hook that is called before bumps are committed and pushed. Allows users to modify or create files based on the entire release instead of per package.
> feat: Adds precommit hook

- .github/workflows/pr.yml
- change/beachball-bb84d74d-c4d5-49bd-9671-d01dfe9c962c.json
- src/__e2e__/change.test.ts
- src/changefile/getChangedPackages.ts
By default, [github `actions/checkout`](https://github.com/actions/checkout) only fetches the current merge ref of the PR (no history and no other branches). This causes problems for `beachball check`, because it doesn't have all the history that it needs to compare against.
These problems have existed for quite some time, in any repo using `actions/checkout` > v1 without `fetch-depth: 0`. And the `workspace-tools` git changed files helpers were hiding the issue by returning empty arrays if git commands failed.
Fix is to add explicit checks on the beachball side for various conditions related to missing history. If history is missing and fetching is enabled, it will fetch the extra history. If fetching is disabled, it will print informative error messages.
(You can see that it works …
> Fix handling of shallow clones when checking for change files

- change/beachball-8b44483a-cbcf-4bce-a338-df4c3eef32fb.json
- src/changefile/promptForChange.ts
- src/types/ChangeFilePrompt.ts
Previously, if the user did ctrl+c partway through the change file prompt, beachball would write all the change files so far. This could include partial change files (missing the message) if the cancellation occurred partway through the questions for a package. For example, it might write a change file like:
```json
{
"type": "none",
"packageName": "beachball",
"email": "whatever",
"dependentChangeType": "none"
}
```
This PR switches to a more accurate cancellation check (via prompts options), with NO change files written if it's triggered.
> Don't write change files if prompt is cancelled

- change/beachball-170dbbeb-641f-4ec6-9d18-622916d40210.json
- src/cli.ts
- src/options/getDefaultOptions.ts
- src/types/BeachballOptions.ts
- src/validation/validate.ts
If multiple package names are passed to `--package`, all of them should be validated.
I also fixed a couple of missing `await`s in the main CLI function.
> Add validation for multiple specified packages

- change/beachball-2c265b94-ba34-484c-9f99-0221c36c8d52.json
- src/__fixtures__/packageInfos.ts
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/__tests__/changefile/getDisallowedChangeTypes.test.ts
- src/__tests__/publish/tagPackages.test.ts
- src/__tests__/publish/toposortPackages.test.ts
- src/changefile/getDisallowedChangeTypes.ts
Add tests for `getDisallowedChangeTypes`, as part of adding tests for the `change` command.
As part of those tests, I added a `makePackageInfos` helper for type safety and conciseness, and updated some of the other tests to use that where relevant.
> Add tests for getDisallowedChangeTypes

- .vscode/launch.json
- change/beachball-00860b08-4d59-4349-ade2-61216f881b99.json
- package.json
- src/__e2e__/change.test.ts
- src/__fixtures__/mockLogs.ts
- src/__fixtures__/mockStdin.ts
- src/__fixtures__/mockStdout.ts
- src/__tests__/changefile/promptForChange.test.ts
- src/__tests__/changefile/promptForChange_getChangeFileInfoFromResponse.test.ts
- src/__tests__/changefile/promptForChange_getQuestionsForPackage.test.ts
- src/__tests__/changefile/promptForChange_promptForPackageChange.test.ts
- src/changefile/promptForChange.ts
- src/commands/change.ts
- yarn.lock
This PR adds unit and E2E tests for the `change` command. To add unit tests, it was necessary to split the `promptForChange` helper into several parts, and I moved all the pieces that read from the filesystem into the `change` command function.
One of the motivations for this was to ensure that the autocomplete freeform input hack doesn't break with new `prompts` versions, so it was important to test the actual input part in a realistic manner. Thankfully `prompts` provides options for custom `stdin`/`stdout` streams, and I used a variant of [`mock-stdin`](https://www.npmjs.com/package/mock-stdin) plus a custom writable stream that just saves chunks written to it. 
One thing to note about input mocking is that to simulate the user typing (where characters are entered and processed …
> Add tests for change command

- change/beachball-1c33a622-edd0-4089-bfef-1010b43a585a.json
- package.json
- src/__fixtures__/tmpdir.ts
- yarn.lock
I moved the `os.tmpdir()` normalization logic to a [new package](https://www.npmjs.com/package/normalized-tmpdir), so use that in beachball.
> Use normalized-tmpdir in tests

- change/beachball-9dd923c9-890e-453f-8aa5-ef4f324cd61a.json
- src/options/getDefaultOptions.ts
- src/packageManager/packagePublish.ts
- src/publish/bumpAndPush.ts
- src/types/BeachballOptions.ts
Building on top of using timeouts for git operations, here this PR introduced a new flag `gitTimeout` to decouple the publish and git timeout.
> New timeout flag for git push

- src/__fixtures__/repository.ts
- src/__fixtures__/repositoryFactory.ts
Cleaning up test fixtures is unnecessary in CI because all the fixtures use unique temp directories (no collisions) and the agents are wiped after each job, so manually deleting the files just slows things down a bit.
> Skip test fixture file cleanup on CI

- .github/workflows/pr.yml
~~`yarn install` is super slow on Windows CI machines, so try using midgard-yarn to speed it up.~~
That didn't help...trying using [`actions/setup-node`](https://github.com/actions/setup-node)'s `cache` option instead?
> Speed up CI

- src/__e2e__/bump.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__fixtures__/mockLogs.ts
- src/__functional__/monorepo/getPackageInfos.test.ts
- src/__functional__/validation/isChangeFileNeeded.test.ts
- src/__tests__/changefile/promptForChange_getQuestionsForPackage.test.ts
- src/__tests__/publish/performPublishOverrides.test.ts
- src/__tests__/publish/toposortPackages.test.ts
Tests using `expect(...).toThrow()` should always check for a specific error message to avoid hiding unexpected errors.
Simplify the mock log setup.
And a few other small fixes.
> Some test cleanup

- change/beachball-e71eeee6-a3d6-4cc5-9205-a53d327dcf03.json
- scripts/jestSetup.js
- src/bump/performBump.ts
- src/bump/setDependentVersions.ts
- src/bump/setDependentsInBumpInfo.ts
- src/publish/toposortPackages.ts
- Proper types and simpler code when iterating over all dep types (prod/dev/peer)
- Reduce nesting levels of `if` statements for readability
- Use `Object.entries()` when iterating over both keys and values
- Use some new syntax and methods where relevant (e.g. `??=`, `flatMap`)
> Simplify some logic in bump and publish

- change/beachball-9cd18eea-64c8-4889-ba02-9e881acdabd9.json
- src/__tests__/publish/tagPackages.test.ts
- src/changelog/getPackageChangelogs.ts
- src/changelog/mergeChangelogs.ts
- src/changelog/renderJsonChangelog.ts
- src/git/generateTag.ts
- src/publish/bumpAndPush.ts
- src/publish/tagPackages.ts
Make the code for git tag creation during publish less confusing by combining the two related functions and adding comments.
Also move the git tag name helper from the `src` root to a folder `src/git`.
> Combine and add comments for git tag methods, and move tag helper

- change/beachball-41697bc4-654b-469a-a08f-75705c9c34f0.json
- src/__e2e__/getChangedPackages.test.ts
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__fixtures__/mockLogs.ts
- src/__fixtures__/npmShow.ts
- src/__fixtures__/registry.ts
- src/changefile/getChangedPackages.ts
Use correct singular/plural with numbers in `getChangedPackages` logging and add a lot more tests for basic cases that were missing coverage.
> Improve getChangedPackages logging and add more tests

- change/beachball-d7948994-9dad-4ef4-b9a9-2d705d933810.json
- src/__functional__/monorepo/getPackageInfos.test.ts
- src/monorepo/getPackageGroups.ts
- src/monorepo/getPackageInfos.ts
Previously, `getPackageGroups` and some of the `getPackageInfos` helpers would throw or exit on the first detected error, which could hide later errors and require more overall time spent debugging.
This PR updates those functions to check for and report all errors before exiting. I also added early bailouts for "base cases" of those functions to reduce nesting and increase readability.
> Report all package/group validation errors instead of short circuiting

- change/beachball-6aa96220-94df-4c01-9f39-bef7a7b27685.json
- src/__fixtures__/npmShow.ts
- src/__fixtures__/repository.ts
- src/__fixtures__/repositoryFactory.ts
- src/env.ts
- src/git/gitAsync.ts
- src/options/getCliOptions.ts
- src/options/getDefaultOptions.ts
- src/options/getPackageOptions.ts
- src/options/getRepoOptions.ts
- src/packageManager/listPackageVersions.ts
Move most environment variable access to a file `env.ts`. This allows type checking (prevents typos in names), fallbacks, and compound variables like `isCI` which take into account multiple platforms' variables.
> Centralize handling of environment variables

- change/beachball-352b1a99-a2ae-4ba6-b8c1-7d3ed1a2e44d.json
- src/__e2e__/publishE2E.test.ts
- src/__fixtures__/mockNpm.ts
- src/__fixtures__/npmShow.ts
- src/__functional__/changefile/readChangeFiles.test.ts
- src/__tests__/packageManager/listPackageVersions.test.ts
- src/__tests__/publish/getNewPackages.test.ts
- src/commands/publish.ts
- src/packageManager/listPackageVersions.ts
- src/publish/getNewPackages.ts
- src/types/BeachballOptions.ts
Add types and simplify a couple things in `listPackageVersions`, ad add a test. This is a basic enough function that it's possible to mock npm return values for speed, rather than using the fake registry.
Also simplify things and add a test for `getNewPackages`.
Finally, I noticed there was a lack of publish E2E coverage for basic monorepo scenarios, so I added tests for the following:
- Publish only the changed packages in a monorepo
- Publish dependents of changed packages in a monorepo
- Publish new non-modified packages in a monorepo (test `new` option)
> Minor cleanup and tests for listPackageVersions

- change/beachball-8a3c9880-68c8-497f-94e2-c49747393de6.json
- src/commands/publish.ts
- src/logging/format.ts
- src/publish/publishToRegistry.ts
- src/publish/shouldPublishPackage.ts
- src/publish/validatePackageDependencies.ts
- src/publish/validatePackageVersions.ts
Add more logs (and more line breaks) and reformat/group some existing logs for improved readability. Specifically for various package validation steps, it's easier to read the logs if the successful and error or skipped packages are grouped together as a list under a heading rather than interleaved or printed with lots of repeated text.
> Improve logging during publishing

- change/beachball-7aca6811-7db0-44c1-810b-1f4a16006014.json
- src/bump/bumpMinSemverRange.ts
- src/bump/bumpPackageInfoVersion.ts
- src/bump/setGroupsInBumpInfo.ts
- src/bump/updateRelatedChangeType.ts
- src/changelog/writeChangelog.ts
- src/logging/format.ts
- src/monorepo/getPackageGroups.ts
- src/publish/bumpAndPush.ts
- src/publish/displayManualRecovery.ts
- src/publish/getPackagesToPublish.ts
- src/publish/validatePackageDependencies.ts
- src/publish/validatePackageVersions.ts
- src/validation/areChangeFilesDeleted.ts
- src/validation/isChangeFileNeeded.ts
- src/validation/isValidChangeType.ts
- src/validation/isValidChangelogOptions.ts
- src/validation/isValidGroupOptions.ts
- src/validation/validate.ts
Previously, a lot of the validation steps would immediately call `process.exit(1)` on failure, which is not helpful because it could hide future errors. Some validation helpers would even short circuit on the first individual package with an error. Also, there were some expensive calculations such as package infos and package groups being run multiple times.
This PR switches around some of the ordering for validation and adds more logging:
- Calculate package infos and groups in the main `validate` method and pass them to helpers
- Modify all validation helpers that iterate over anything to accumulate errors and log them together at the end for readability
- If there's an individual error, continue through validation as far as possible (to show any additional errors) instead of exiting …
> Validation improvements

- change/beachball-47472917-5374-4d55-a134-51a4ddbefa85.json
- package.json
- src/publish/toposortPackages.ts
- yarn.lock
Typescript 4.5 has been out for quite awhile now, and the API surface of beachball types is pretty minimal, so it's probably safe to update. 
(It would likely be okay to go even newer than this, but I specifically wanted `Awaited` which is in 4.5.)
> Update to typescript 4.5

- change/beachball-9bdf704a-61ed-4b77-8dfa-26bc583976fa.json
- docs/cli/change.md
- docs/cli/options.md
- src/__e2e__/getChangedPackages.test.ts
- src/changefile/getChangedPackages.ts
- src/commands/change.ts
- src/packageManager/listPackageVersions.ts
- src/validation/validate.ts
Add an `--all` option for the `change` command to generate change files for all packages (or all in-scope packages, if `scope` is specified).
> Add --all option for change command

- change/beachball-811d2893-9f79-4cf7-a6b0-83cc24615cf6.json
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__fixtures__/mockNpm.ts
- src/__fixtures__/npmShow.ts
- src/__functional__/packageManager/packagePublish.test.ts
- src/__tests__/packageManager/listPackageVersions.test.ts
- src/__tests__/publish/getNewPackages.test.ts
- src/__tests__/publish/validatePackageVersions.test.ts
- src/bump/performBump.ts
- src/commands/init.ts
- src/commands/sync.ts
- src/packageManager/listPackageVersions.ts
- src/packageManager/npm.ts
- src/packageManager/packagePublish.ts
Remove the synchronous `npm` helper, and rename `npmAsync` to just `npm`. This is mainly to simplify some things in future tests.
Also remove some tests in `packagePublish` that were actually just verifying that the correct options were passed to `npm publish`, which is now covered by the `getNpmPublishArgs` tests.
(Most of the extra changes were triggered by updates to the `npmShow` test helper to make it asynchronous and tweak the signature.)
> Run all npm commands async

- jest.config.js
- src/__fixtures__/mockNpm.test.ts
- src/__fixtures__/mockNpm.ts
- src/__tests__/packageManager/listPackageVersions.test.ts
- src/__tests__/publish/getNewPackages.test.ts
- src/__tests__/publish/validatePackageVersions.test.ts
Update the mock npm helper to support `npm publish` in addition to `npm show`, and add more customization ability and comments.
This is to support a future change to make most of the publishing-related tests use this npm mock rather than interacting with a verdaccio registry via the npm CLI, which is extremely slow and limits the number of tests that can reasonably be added.
> Improve mock npm and support mock publishing

- change/beachball-d1b2b2d2-c6cf-4ada-820d-bf5ed03fcce7.json
- src/__e2e__/publishE2E.test.ts
- src/__e2e__/publishRegistry.test.ts
- src/__e2e__/syncE2E.test.ts
- src/__fixtures__/mockNpm.test.ts
- src/__fixtures__/mockNpm.ts
- src/__fixtures__/npmShow.ts
- src/__fixtures__/repositoryFactory.ts
- src/__functional__/packageManager/packagePublish.test.ts
- src/bump/callHook.ts
- src/bump/performBump.ts
- src/options/getDefaultOptions.ts
- src/packageManager/packagePublish.ts
- src/publish/publishToRegistry.ts
- src/types/BeachballOptions.ts
- src/validation/validate.ts
Display a specific helpful error message and (mostly) prevent retries in the following cases:
- `ENEEDAUTH`: Not logged in/token not provided
- `EPUBLISHCONFLICT`: Version already exists in registry
- `code E404`: Usually indicates an issue with an auth token (expired or improper scopes)
- Also add a specific note if the operation timed out (retries are allowed in this case).
As part of this, I refactored the publish retries and error handling logic to be centralized in `packagePublish` (for easier testing), rather than split between there and `publishToRegistry`. 
(Another common case is that the token variable name in a workflow/pipeline is invalid, which depending on the syntax may either result in the token being an empty string from an unset variable, or a failed variable …
> Better handling of some known publishing issues

- change/beachball-b16e6b4f-dc7c-47e6-bd0f-3722b5c2c112.json
- src/__e2e__/bump.test.ts
- src/bump/callHook.ts
- src/types/BeachballOptions.ts
Same end goal as #896 
We are trying to have our yarn 1 repo be able to:
Locally, refer to local workspace package version using the * version
At publish time, change to ^x.y.z, where x.y.z is the post-bump version
To accomplish this, we are hoping to use the prepublish hook to change the internal packages to ^x.y.z. Passing the post-bump versions to the prepublish hook would allow for this to happen without file i/o on our end
> Pass packageInfos into prepublish, postpublish, and postbump hooks

- change/beachball-b0d4d413-19f2-4277-8fe3-4a6a80933ad2.json
- src/__fixtures__/packageInfos.ts
- src/__tests__/publish/performPublishOverrides.test.ts
- src/publish/performPublishOverrides.ts
- src/types/PackageInfo.ts
Extract the types of `PackageJson.publishConfig` into a separate `PublishConfig` type.
Fix the `performPublishConfig` tests to not write to the filesystem, and add more coverage.
> Publish config type updates, and performPublishConfig tests

- change/beachball-f146e707-ddd6-42bd-8918-391c07aaeabf.json
- src/__functional__/packageManager/packagePublish.test.ts
- src/packageManager/npmArgs.ts
- src/packageManager/packagePublish.ts
- src/types/NpmOptions.ts
- Include the package root directory in the pre-publish message
- If `--verbose` is set, increase the npm logging level to `notice`
- Add a specific check (and prevent retries) for E403
> Add more logging during publishing

- change/beachball-349b5c41-3054-4f34-b30d-1413216f67e9.json
- src/__functional__/options/getCliOptions.test.ts
- src/cli.ts
- src/options/getCliOptions.ts
- src/types/BeachballOptions.ts
- Ensure that that text values `true` and `false` are handled as booleans
- Add explicit expected option types for all known CLI options
- Refine the returned value to not include camel case or aliased keys
- Add tests for `getCliOptions` (this will help ensure predictable behavior with future `yargs-parser` upgrades or if we change to another parser like `commander`)
> CLI options: improve handling of booleans and other cases

- change/beachball-4182291c-ee3b-455f-8d64-bf4213a49c76.json
- src/__tests__/monorepo/isPathIncluded.test.ts
- src/monorepo/getScopedPackages.ts
- src/monorepo/isPathIncluded.ts
- src/types/BeachballOptions.ts
- src/types/ChangelogOptions.ts
Update `getScopedPackages` to skip the step of checking for package inclusion if there are only *exclusion* (negated) scope patterns specified. This should provide a minor efficiency improvement in large repos.
Also update `isPathIncluded`'s `include` parameter (and the group `include` options that use it) to allow passing `true` instead of include pattern(s), to include all packages except those specified by `exclude` and skip some pattern checks.
Other changes:
- Simplify `isPathIncluded` logic 
- Add more tests for `isPathIncluded`
- Update docs for group `exclude` to clarify that exclusions must be specified as negated patterns for now (this is an incorrect design which should be fixed in a major version, tracked by #916)
> Minor improvements to path include/exclude logic

- change/beachball-a311609d-38f8-420d-8cd7-a5a98e5876ba.json
- src/__functional__/changelog/writeChangelog.test.ts
- src/changefile/readChangeFiles.ts
- src/types/BeachballOptions.ts
Beachball has a nice feature that lets you run custom transformations on change files. Our team is using them today to augment beachball changelogs with links to the ADO PRs corresponding to the release.
That being said, in the current implementation we are having a negative impact on local beachball change times. This is because beachball runs this transform during commands like change and publish. For our particular transform, we don't want to run it during yarn change, since that runs before we have a merged PR.
With this change, the custom beachball change file transform can decide to skip the expensive step to compute the PR URL if we are not running in the context of a beachball publish
> Add context on current running command for change file transforms

- change/beachball-f8eb13a7-d410-4a2e-92e3-0e95346da8c5.json
- src/__e2e__/bump.test.ts
- src/bump/bumpPackageInfoVersion.ts
- src/types/BeachballOptions.ts
[Pre-release identifier](https://docs.npmjs.com/cli/v6/using-npm/semver#prerelease-identifiers) in semver allows to control the identifier base when bumping a pre-release package.
With beachball, the identifier base is always set to zero; the goal of this PR is to support zero-based, one-based and no identifier base.
The options for the identifier base are "0", "1" and false.
Here is how it works with semver:
> Adding support for identifier base

- change/beachball-f4d4d8d6-7911-4657-87f3-f552ce6eed0f.json
- src/bump/bumpPackageInfoVersion.ts
My last PR allowed us to add the options for new PrereleaseTypes: Premajor, preminor and prepatch. But the if statement in the current code overruled these types when the prereleasePrefix is checked.
In my opinion this check should change since having this means you can't add the prerelease prefix to the config cause it would handle every change as a prerelease. But since changing that would be a breaking change I added a different if check that should keep working in the current use cases
> Ensure it bumps premajor, preminor and prepatch with a prereleasePrefix

- change/beachball-777e7bf0-8855-48ac-9337-c6578415bc13.json
- src/packageManager/npm.ts
Set shell: true when spawning npm commands. This is required for Windows after a [Node security fix](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2).
> Run npm with shell: true

- README.md
- change/beachball-3a1535e5-d3c6-4f91-a673-17f6e527edb3.json
- src/env.ts
- src/packageManager/listPackageVersions.ts
**Description:** 
This update introduces the ability to specify the NPM_CONCURRENCY environment variable, which controls the concurrency level when listing package versions from NPM. The current default settings are either 2 or 5.
**Usage:**
To adjust the concurrency, set the NPM_CONCURRENCY environment variable to the desired value. This change enables users and CI/CD pipelines to override the default concurrency levels when running the beachball sync command.
**Why This Is Necessary:**
For large monorepos, the beachball sync process can take an excessive amount of time due to the high volume of packages. By allowing a higher concurrency setting, this update can help improve performance and reduce the overall sync time.
**Considerations when overriding this value:**
- Network Latency
- …
> feat: Enable override to NPM_CONCURRENCY defaults through env variable

- change/beachball-e6b4755a-c316-496c-8094-19d6ec7f7201.json
- src/__functional__/changelog/__snapshots__/writeChangelog.test.ts.snap
- src/__tests__/changelog/__snapshots__/renderChangelog.test.ts.snap
- src/__tests__/changelog/renderChangelog.test.ts
- src/changelog/renderChangelog.ts
- src/changelog/renderMainHeader.ts
- src/types/ChangelogOptions.ts
Implements the changes discussed in #975 including:
- Comments out the  `` part of the changelog by default, since it's mostly intended for someone who's trying to edit the markdown source.
- Supports changing the default `<h1>` content `# Changelog - <@package-name>` via a `renderMainHeader` changelog option.
> Changelog options render main header

- change/beachball-777cc61a-b404-4be0-94f5-bd154643ecaa.json
- src/bump/bumpInPlace.ts
- src/bump/gatherBumpInfo.ts
- src/bump/setDependentVersions.ts
- src/bump/setDependentsInBumpInfo.ts
- src/bump/setGroupsInBumpInfo.ts
- src/bump/updateRelatedChangeType.ts
- src/changefile/changeTypes.ts
- src/changelog/mergeChangelogs.ts
- src/types/BumpInfo.ts
- src/types/ChangelogOptions.ts
`continue` rather than `return` when updating calculated change types if one change file referenced a package that doesn't exist. (This was probably introduced when converting a `.forEach` to `for..of`.)
In practice, this shouldn't have caused issues because `readChangeFiles` already checks for nonexistent packages, but the code was still incorrect and should be fixed.
Also clarify some comments and types in other files in the bump process.
> Fix early bail bug in updateRelatedChangeType

- change/beachball-fc33dd32-5877-497d-9032-836787d0c08d.json
- src/__functional__/changelog/writeChangelog.test.ts
- src/__tests__/changelog/__snapshots__/renderPackageChangelog.test.ts.snap
- src/__tests__/changelog/renderPackageChangelog.test.ts
- src/changelog/renderPackageChangelog.ts
#944 added change types premajor/preminor/prepatch, but they weren't being included in the changelog.
> Include pre* changes in changelog

- change/beachball-5d27a64f-c23d-4ae8-8848-d424d7fef666.json
- src/__fixtures__/changeFiles.ts
- src/__fixtures__/changelog.ts
- src/__fixtures__/repository.ts
- src/__functional__/changefile/readChangeFiles.test.ts
- src/__functional__/changefile/writeChangeFiles.test.ts
- src/__functional__/changelog/__snapshots__/writeChangelog.test.ts.snap
- src/__functional__/changelog/writeChangelog.test.ts
- src/bump/performBump.ts
- src/changelog/writeChangelog.ts
Fix an edge case and improve changelog tests.
Scenario: Suppose there's a changelog group with `masterPackageName: 'foo', changelogPath: 'packages/foo'`. This is supposed to make the grouped changelog be written in place of `foo`'s normal changelog. But if `foo` has no changes besides dependency bumps, and there are no changes in other grouped packages (so the grouped changelog isn't written), previously the dependency bumps from `foo`'s normal changelog would be prepended to what's supposed to be a grouped changelog. (See [this test case](https://github.com/microsoft/beachball/pull/984/files#diff-1819960692d0b38e963fb83251d573780176b3d9a0923f04a27de0a7190cd209R384) for a clearer example.)
This PR fixes the issue by *always* skipping potential grouped changelog paths when writing package …
> Prevent accidentally writing dep bumps to grouped changelog (and test improvements)

- change/beachball-d1d64636-b7a3-490c-80a1-af0e305a05ca.json
- src/validation/validate.ts
#878 introduced a bug where beachball would no longer exit with an error if there were invalid change files (though it would log messages). 
This PR changes the ordering of some checks so that `if (hasError) process.exit(1)` comes *after* all the other checks that set `hasError`.
> Exit with an error on invalid change files

- README.md
- change/beachball-6783701e-869a-4075-b933-f3ea58db98f7.json
- docs/cli/options.md
- src/bump/bumpPackageInfoVersion.ts
- src/publish/getNewPackages.ts
- src/publish/publishToRegistry.ts
- src/types/BeachballOptions.ts
- src/types/BumpInfo.ts
Update a few comments, types, and internal names.
Update the readme to clarify that beachball does not have a public API (this has always been the case).
Remove the misleading and usually-unnecessary `--new` option from the doc site. This option incurs an extra cost during publishing (fetch every package that's *not* being published from the registry) and is unnecessary if the repo runs `beachball check` in PR builds to ensure that all new and changed packages have change files.
> Minor doc updates

- change/beachball-848fed39-4933-483a-a038-1470bebe299b.json
- src/__tests__/bump/updateRelatedChangeType.test.ts
- src/__tests__/publish/tagPackages.test.ts
- src/bump/gatherBumpInfo.ts
- src/bump/getDependentsForPackages.ts
- src/commands/publish.ts
- src/publish/getPackagesToPublish.ts
- src/publish/publishToRegistry.ts
- src/publish/tagPackages.ts
- src/types/BumpInfo.ts
`BumpInfo.newPackages` is only set and used during the actual steps of bumping on disk and publishing, not the initial bumping in-memory. Move it to a separate type `PublishBumpInfo` (not a great name...) and update the relevant functions to clarify where it's used.
I also added a console log before the operation starts with a warning against using it, because it's usually unnecessary and potentially pretty expensive (fetch *every unmodified package* from npm).
(It's unclear if determining the new packages strictly *needs* to be done only during publish, but it is potentially pretty expensive, and it's always been part of only the publish command since it was added in #234.)
> Remove newPackages from main BumpInfo

- change/beachball-68aac7dd-5676-4f86-af7f-4c2ee46d08f7.json
- src/bump/performBump.ts
- src/bump/updateLockFile.ts
- src/bump/updatePackageJsons.ts
- src/commands/sync.ts
Move the utilities for updating package.jsons and the lock file after bumping into their own files. This makes the code easier to read.
> Move post-bump package updating utils to separate file

- change/beachball-8dc8dc7e-34ec-4fe1-be0b-8a2af1f96f16.json
- package.json
- src/__e2e__/publishE2E.test.ts
- src/__fixtures__/mockNpm.test.ts
- src/__fixtures__/mockNpm.ts
- src/__tests__/monorepo/getPackageGraph.test.ts
- src/bump/callHook.ts
- src/bump/performBump.ts
- src/monorepo/getPackageDependencyGraph.ts
- src/monorepo/getPackageGraph.ts
- src/options/getCliOptions.ts
- src/options/getDefaultOptions.ts
- src/packageManager/packagePublish.ts
- src/publish/publishToRegistry.ts
- src/publish/toposortPackages.ts
- src/types/BeachballOptions.ts
- yarn.lock
This pull request introduces a new concurrency flag to the Beachball package, updates dependencies, and refactors the `publish` command tests to support concurrency. Additionally, it includes new tests for the `getPackageGraph` function.
* Added concurrency flag to the Beachball package, by default it is set to 1 to keep backwards compatibility with previous behavior while we test new behavior.
* Added `p-graph` dependency for running publishing command and hooks in parallel but in order of dependency graph.
* Added comprehensive tests for `getPackageGraph` in `getPackageGraph.test.ts` to validate package sorting and handling of dependencies.
* Added E2E tests for `publish` command to validate all existing scenarios for both concurrency being 1 and greater.
* Modified `callHook` function …
> Add concurrency flag

- change/beachball-d06fb0b6-4977-44f2-9e5f-cc4f2ca0b5f5.json
- src/__functional__/changelog/__snapshots__/writeChangelog.test.ts.snap
- src/__functional__/changelog/writeChangelog.test.ts
- src/__tests__/changelog/__snapshots__/renderChangelog.test.ts.snap
- src/__tests__/changelog/renderChangelog.test.ts
- src/__tests__/changelog/renderJsonChangelog.test.ts
- src/changelog/renderChangelog.ts
- src/changelog/renderJsonChangelog.ts
- src/changelog/writeChangelog.ts
- src/types/ChangelogOptions.ts
Add an option `changelog.maxVersions` which truncates the number of versions stored in `CHANGELOG.md` and `CHANGELOG.json`.
Related to #978
> Add option changelog.maxVersions

- .vscode/launch.json
- change/beachball-ba7bb90f-ba01-4c9b-84ac-e054aa4db235.json
- change/beachball-c1b55758-27ac-4dc8-b073-8380c991c183.json
- jest.config.js
- package.json
- src/__fixtures__/changelog.ts
- src/__fixtures__/createTestFileStructure.ts
- src/__fixtures__/tmpdir.ts
- src/__functional__/changelog/prepareChangelogPaths.test.ts
- src/__functional__/changelog/writeChangelog.test.ts
- src/changefile/writeChangeFiles.ts
- src/changelog/prepareChangelogPaths.ts
- src/changelog/writeChangelog.ts
- src/types/ChangelogOptions.ts
- yarn.lock
Add an option `changelog.uniqueFilenames` which adds an 8-character ~~random~~ suffix to the end of the changelog filename (before the extension): e.g. `CHANGELOG-abcd1234.md`.
EDIT: After discussion, the suffix is now the first 8 characters of the MD5 hash digest of the package name.
This will stay stable between commits, and any existing changelog files will be renamed when modified. Existing suffixed files should also be renamed if the package is renamed. (I'm guessing 8 characters is good enough, but we could also use 12 or more.)
This is one option for working around an issue with Git: its default hash algorithm only considers the last 16 characters of filenames, which can lead to collisions and inefficient packing when many files have similar names, which then leads to extreme …
> Add option to use hash in changelog filenames

- change/beachball-fbe57b6e-69d7-4628-8c28-6000d9e9449b.json
- src/__tests__/changefile/getQuestionsForPackage.test.ts
- src/__tests__/changefile/promptForChange.test.ts
- src/__tests__/changefile/promptForChange_promptForPackageChange.test.ts
- src/changefile/getQuestionsForPackage.ts
- src/changefile/promptForChange.ts
Move the prompt helper `getQuestionsForPackage` to its own file in preparation for other changes.
> Move getQuestionsForPackage to its own file

- change/beachball-053e98de-4e97-4d4e-bc5d-ee4787e38a7f.json
- src/packageManager/packagePublish.ts
npm 10 uses `E409` in the publish output if the version already exists.
> Fix publish failure package exists check to work with npm 10

- change/beachball-8be53545-c527-40e6-a9f6-65cdb5dcfd3c.json
- src/__e2e__/publishE2E.test.ts
- src/bump/updateLockFile.ts
With modern package managers (not yarn v1/old npm) that include local monorepo versions in the lock file, after `npm publish`, it's necessary to run the package manager again to update the lock file. We should entirely skip that check when running tests for now, for efficiency. (This becomes relevant in the beachball next branch that updates to yarn v4.)
Also update the package publish tests to remove concurrent versions from cases where (upon further inspection) they're not adding value and just slowing things down.
> Never update lock file after publish when running tests

- change/beachball-d0b88f44-aa23-4ab8-9baf-35466cb0ac7f.json
- package.json
- src/__fixtures__/mockLogs.ts
- src/__tests__/publish/tagPackages.test.ts
- yarn.lock
This dev dep was only being used for types, and those types are now available on the global `jest` object.
> Remove jest-mock dev dep

- change/beachball-05fd5096-f4e9-4726-9ce4-1a19e197f1bb.json
- src/__tests__/changelog/renderChangelog.test.ts
- src/__tests__/changelog/renderPackageChangelog.test.ts
- src/changelog/renderChangelog.ts
- src/changelog/renderMainHeader.ts
- src/changelog/renderPackageChangelog.ts
- src/types/ChangelogOptions.ts
Previously the render functions in `ChangelogOptions` could only return a promise. There's no reason they can't be synchronous, so update the types to allow either one.
> Allow changelog render functions to be synchronous

- change/beachball-c96251d0-33c6-465e-b32e-d7f0e1b1aecd.json
- src/__e2e__/validate.test.ts
- src/cli.ts
- src/types/BeachballOptions.ts
- src/validation/validate.ts
Previously `validate()` had an option `allowFetching` (default true) which was hiding the actual behavior. It was also not precise about which commands needed to validate dependencies or not. Update the options as follows:
- `checkChangeNeeded`: check whether change files are needed (`change`, `check`)
- `allowMissingChangeFiles`: used with above, but don't error on missing change files (`change`)
- `checkDependencies`: perform an in-memory bump and validate that no package to be bumped (including dependents) have private dependencies (most commands but `change`). Previously in some cases, `change` would include this check, which just slows it down and isn't needed.
As a side effect of the confusing options, previously the `bump` command was checking for whether change files are needed, …
> Clarify internal validation logic + don't check for change needed in bump command

- change/beachball-b77b0445-c306-4b28-989e-474c4719a890.json
- src/types/BeachballOptions.ts
There were a bunch of properties defined only in `CliOptions` which could also make sense in a config file, and therefore really belong in `RepoOptions`. Move those properties to `RepoOptions` so that they show up in intellisense for config files.
> Add more properties to RepoOptions instead of just CliOptions

- change/beachball-828497fb-eabf-414f-921a-503cd3c291f5.json
- src/bump/updateRelatedChangeType.ts
The `updateRelatedChangeType()` method can be called with individual packages or a list of packages. In either case, this presents a _minimum_ of quadratic performance as it does a breadth-first-search of the dependency graph starting at each input package, one a at a time. For example, in an internal monorepo that recently had a Typescript upgrade initiate 3000+ package updates at once, `bumpInPlace()` calls this method 3000+ times and each does a bunch of repeated work.
To resolve this issue, we will need to combine things into a single DAG walk. That is a more involved change that will take more time and testing. I will report back later. We need something to resolve the pain sooner.
The current implementation has a more immediate issue: the quadratic behavior is actually sometimes …
> updateRelatedChangeTypes: fix cubic behavior

- change/beachball-ec0a58b8-699d-4d02-832d-e3ae639b0f70.json
- src/__tests__/changelog/getPackageChangelogs.test.ts
- src/changelog/getPackageChangelogs.ts
- src/types/ChangeInfo.ts
- src/types/ChangeLog.ts
- src/types/ChangelogOptions.ts
Add an option `options.changelog.includeCommitHashes` which defaults to true but can be used to disable fetching and writing commit hashes to the changelog.
Fixes #1048
> Add option to disable commit hashes in changelogs

- change/beachball-7bcba9ba-c794-4d60-9a28-2141f263b8ee.json
- src/__fixtures__/mockNpm.ts
- src/__tests__/packageManager/listPackageVersions.test.ts
- src/packageManager/listPackageVersions.ts
`npm show` allows requesting only specific properties, so when getting the list of existing `versions` and `dist-tags`, we should request only those properties.
> Only request the necessary properties with npm show

- README.md
- change/beachball-a4ff6165-e9ef-4ae7-9406-a6765d46379c.json
- src/__e2e__/syncE2E.test.ts
- src/__functional__/packageManager/packagePublish.test.ts
- src/__tests__/packageManager/listPackageVersions.test.ts
- src/__tests__/packageManager/npmArgs.test.ts
- src/__tests__/publish/getNewPackages.test.ts
- src/__tests__/publish/validatePackageVersions.test.ts
- src/env.ts
- src/options/getCliOptions.ts
- src/options/getDefaultOptions.ts
- src/packageManager/listPackageVersions.ts
- src/types/BeachballOptions.ts
- src/types/NpmOptions.ts
Add an option `npmReadConcurrency` which controls the number of simultaneous `npm show` requests when getting current package versions from the registry. This replaces the `NPM_CONCURRENCY` env.
> Add npmReadConcurrency option
