change/beachball-2019-07-18-12-30-02-fixShouldPublish.json, packages/beachball/src/getChangedPackages.ts
Slight error in my shouldPublish option logic, which caused the option to not work correctly.
=> Fix shouldPublish option

azure-pipelines.yml, change/beachball-2019-08-21-15-19-56-merge-base.json, packages/beachball/jest.config.js, packages/beachball/package.json, packages/beachball/src/fixtures/repository.ts, packages/beachball/src/validation.test.ts, yarn.lock
This tests only the most basic scenario, but is a starting place.
Next steps:
- validate more complicated scenarios
- clean up temp folders after test runs
=> Integration tests

change/beachball-2019-09-25-13-41-05-fix-touch.json, packages/beachball/src/fixtures/repository.ts
the touch utility is not available to windows.
=> Fixed yarn test for windows

change/beachball-2019-10-16-13-49-41-changeformat.json, packages/beachball/src/ChangeInfo.ts, packages/beachball/src/bump.ts, packages/beachball/src/changefile.ts, packages/beachball/src/changelog.ts, packages/beachball/tsconfig.json
=> Get rid of reference to file names inside change files!

change/beachball-2019-11-14-13-59-31-fail.json, packages/beachball/src/__tests__/validation.test.ts, packages/beachball/src/cli.ts, packages/beachball/src/fixtures/repository.ts
=> catch errors throw and make sure we exit with a real status code

change/beachball-2019-11-26-12-35-11-bump-peerdeps.json, packages/beachball/src/PackageInfo.ts, packages/beachball/src/__tests__/bump.test.ts, packages/beachball/src/__tests__/publishGit.test.ts, packages/beachball/src/bump.ts, packages/beachball/src/monorepo.ts
If a package is referenced in another's `peerDependencies`, it should also be bumped.
=> Bump peerDependencies

.vscode/launch.json, change/beachball-2020-01-17-10-03-44-infinite.json, packages/beachball/src/__tests__/changefile/getPackageChangeTypes.test.ts, packages/beachball/src/changefile/getPackageChangeTypes.ts, packages/beachball/tsconfig.json
=> Infinite loop fixed about the getting allowed change types during bump

change/beachball-2020-03-31-11-45-33-xgao-fix-none-type.json, packages/beachball/src/validation/isValidChangeType.ts
=> Update isValidChangeType to allow none

change/beachball-2020-04-03-11-21-36-more-types.json, packages/beachball/src/index.ts
Forgot a couple things last time.
=> Export more types

change/beachball-2020-04-15-16-17-01-xgao-fix-sync.json, packages/beachball/src/commands/sync.ts
do not sync if package is out of scope or if is private
=> Sync: honor scope and avoid private package

change/beachball-2020-04-15-19-38-24-xgao-buffer.json, packages/beachball/src/packageManager/npm.ts
to fix publishing failure like: https://uifabric.visualstudio.com/4ed167b9-ac3a-405b-b967-443af8db8961/_apis/build/builds/66254/logs/17
=> 10x spawnSync max buffer

change/beachball-2020-04-17-13-17-56-xgao-check-private.json, packages/beachball/src/__tests__/publish/validatePackageDependencies.test.ts, packages/beachball/src/publish/publishToRegistry.ts, packages/beachball/src/publish/shouldPublishPackage.ts, packages/beachball/src/publish/validatePackageDependencies.ts, packages/beachball/src/publish/validatePackageVersions.ts
=> validate private package not being a dependency before publish

change/beachball-2020-05-21-16-47-21-disallow.json, packages/beachball/src/changefile/getDisallowedChangeTypes.ts, packages/beachball/src/changefile/promptForChange.ts, packages/beachball/src/validation/validate.ts
Fixes #301 - this validates at the validate() function for disallowed package change type.
=> validate the disallowedChangeTypes for publishing

change/beachball-2020-07-20-13-02-48-retry-push.json, packages/beachball/src/publish/bumpAndPush.ts
Adds a retry logic for bumpAndPush so that we can be resilient to any issues with the git race conditions
=> Retry git pushes

change/beachball-2020-09-04-13-43-21-detach.json, src/__e2e__/publishE2E.test.ts, src/commands/publish.ts
After refactoring the branch deletion, we now need to handle the detached head case.
=> Detached HEAD should not affect whether it can publish or not.

change/beachball-2020-09-11-16-37-59-canary.json, package.json, src/__e2e__/publishE2E.test.ts, src/__e2e__/publishGit.test.ts, src/__e2e__/publishRegistry.test.ts, src/bump/performBump.ts, src/cli.ts, src/commands/canary.ts, src/options/getDefaultOptions.ts, src/types/BeachballOptions.ts, tsconfig.json, yarn.lock
run it like this:
`beachball canary --canary-name pr1234`
Fixes #390
=> Canary builds - we should be able to make canary packages now!

change/beachball-2020-09-21-19-41-18-branch-ninja.json, src/publish/bumpAndPush.ts
Hopefully this makes it so we don't over fetch during a publish
=> Branch ninja: be more specific in what the fetch during publish

change/beachball-2cdb51a7-f0f6-4915-97f9-239edee9462c.json, package-lock.json, package.json
Upgrading to the latest yargs version, since we are quite behind. This also helps address some security alerts in Azure Devops repos.
=> Bump yargs version

change/beachball-1ec30d35-b66d-472d-8eb5-39ead7966cd3.json, src/options/getCliOptions.ts
Addresses regression mentioned in the comments to this PR: https://github.com/microsoft/beachball/pull/448.
=> Set disallowedChangeTypes property only if argument is present

change/beachball-04ad5d5c-2356-4afd-a8db-c4781758c88f.json, src/cli.ts, src/commands/init.ts
Simply adds scripts & devDep in the root for beachball.
=> Init command: run this to bootstrap a repo with beachball!

change/beachball-4ad26cd1-13bf-4bdb-b1d8-9a352a378b7f.json, package.json, src/options/getRepoOptions.ts, yarn.lock
This will actually query for the default branch rather than assume!
=> Use default branch

change/beachball-bc8b59dc-37ff-4266-8ec0-cbf4737b6671.json, src/options/getRepoOptions.ts
=> Perf fix for getting repo options (check, change, etc)

.github/workflows/pr.yml
Applying fix described in https://github.com/microsoft/beachball/issues/420#issuecomment-712465458 to beachball itself
=> Fix checkchange in PR workflow

change/beachball-422aaf37-cf2e-47fa-8008-ff3a306e4d9b.json, docs/cli/check.md
=> Add note about setting up check in github actions

change/beachball-63f70df7-cb38-48e9-824e-c169d8e5e484.json, docs/cli/change.md, docs/cli/check.md
=> Fix the broken links to change-files

change/beachball-8f763311-6d52-4d11-9251-47573f456512.json, src/changefile/getChangedPackages.ts, src/changefile/readChangeFiles.ts
=> Improve "Invalid change file" error messages

change/beachball-233e3407-02d4-49a0-8d27-3e07ba813854.json, docs/concepts/bump-algorithm.md, docs/overview/getting-started.md
I guess some of these changes are a matter of taste as well, so feel free to cherry-pick!
=> docs: Fix some typos and language

change/beachball-ece5d61c-c1fa-43c8-aee1-1b519e50e141.json, src/__e2e__/publishE2E.test.ts, src/options/getCliOptions.ts, src/options/getDefaultOptions.ts, src/publish/bumpAndPush.ts, src/types/BeachballOptions.ts
This PR is expected to expose fetch flag and a depth option in CLI which will allow user to specify whether fetch is required in bump and when required what should be the depth of fetch. This is meant to address the issue https://github.com/microsoft/beachball/issues/614
=> Adding no fetch to publish

docs/cli/change.md
This PR attempts to fix the "change file" broken link on [this page](https://microsoft.github.io/beachball/cli/change.html#change).
=> Fix link to change file

change/beachball-f27c9ec4-fecd-477d-91c4-8df3ec849d0f.json, src/publish/bumpAndPush.ts
Fixes https://github.com/microsoft/beachball/issues/680, by adding error handling for git fetch
=> Adding retries for fetch

change/beachball-ef09dabd-ce24-4044-af18-daf358a4f64c.json, src/commands/publish.ts, src/publish/bumpAndPush.ts
Fixes https://github.com/microsoft/beachball/issues/714
=> Adding error handling for publish

change/beachball-df20cdf9-6012-408e-b4ea-24d34d62b84f.json, src/publish/bumpAndPush.ts
Using the timeout option, for setting timeout for git operation. 
This will resolve [this issue](https://github.com/microsoft/beachball/issues/820)
=> Adding timeout for git push

change/beachball-8b09ffe5-dd69-4c08-b86d-1c764a046c97.json, src/bump/performBump.ts
Fixes issue https://github.com/microsoft/beachball/issues/826
=> Handle file deletion scenario

change/beachball-e07eca79-4fc1-4248-97a0-3f45f419754a.json, src/commands/publish.ts, src/publish/bumpAndPush.ts
Fixing a couple small issues I noticed while reading through the publish workflow recently
=> Minor fixes for publish logging and checks

change/beachball-8dfc65fb-0740-4b07-b1d3-ce89e06bfbf0.json, src/bump/performBump.ts
Fixes https://github.com/microsoft/beachball/issues/844
=> Handle private package version update

change/beachball-023338c9-833d-4a94-9808-2983b69bad1b.json, package.json, yarn.lock
Pick up https://github.com/microsoft/workspace-tools/pull/316 to fix #793 for real...
=> Update workspace-tools to fix message suggestions with no commits

docs/.vuepress/config.js, docs/.vuepress/styles/palette.styl, docs/concepts/ci-integration.md
- Use a slightly darker accent color for readability (to fix this properly we'd either need to make a custom vuepress theme with more variation in accents by context, or give up on the "sunny" accent color)
- Fix issue with mismatched h3/h4 tags on CI integration page
- Add types for config file
=> Fix issues with docs

change/beachball-9fba6edb-930b-4f69-9b4f-9ebc978c414f.json, src/bump/performBump.ts, src/packageManager/pnpm.ts, src/packageManager/yarn.ts
This PR fixes issue #769 and also adds support for pnpm lockfile updates.
=> Support updating lockfiles for pnpm and yarn

change/beachball-c1617728-8438-43b9-b556-8e68a117284a.json, src/__e2e__/bump.test.ts, src/bump/performBump.ts, src/bump/setDependentVersions.ts, src/bump/setDependentsInBumpInfo.ts, src/monorepo/infoFromPackageJson.ts, src/publish/performPublishOverrides.ts, src/publish/toposortPackages.ts, src/types/PackageInfo.ts
Currently beachball supports dependencies, devDependencies and peerDependencies. I'm adding optionalDependencies.
=> Support optionalDependencies

change/beachball-811599b0-61ca-46ba-bb8c-f39582ca9e1d.json, docs/yarn.lock, package.json, yarn.lock
Pick up the fix from https://github.com/microsoft/workspace-tools/pull/344 by default and refresh lock files.
=> Update workspace-tools and local deps
